### PR TITLE
Hold matched route full path in the Context

### PR DESCRIPTION
**Pull request by zaynetro**
This is a proposed change to return handler full path from the Context.

### Where it can be useful?

When using lambda functions as a handler names returned from `(*Context).HandlerName` become not lean. With this change it becomes easy to analyse which route was called exactly. This can be useful when trying to find out which routes are not being called in the app.

### Alternatives

It is possible to create a wrapper around route definition:

```go
func logGET(router *gin.Engine, path string, handler func (*gin.Context)) {
    router.GET(path, func (c *gin.Context) {
        // Do something with path
        handler(c)
    })
}

...

logGET(router, "/user/:id", func (c *gin.Context) {
    c.Status(200)
})
```

This approach is doable but considering that Gin already holds full path in its structures I though that it might be better to just expose it.

P.S. README no longer contains any docs so I am not certain where I should document this feature.

### CODE REVIEW

**Comment by thinkerou** [comment]
@zaynetro thanks! ref: #1390 #1447

**Comment by zaynetro** [comment]
Oh, I wasn't aware of multiple previous attempts...

**Comment by thinkerou** [comment]
The pull request benchmark data:
```
➜  go-http-routing-benchmark git:(master) ✗ go test -bench=Gin
#GithubAPI Routes: 203
   Gin: 58480 Bytes

#GPlusAPI Routes: 13
   Gin: 4368 Bytes

#ParseAPI Routes: 26
   Gin: 7744 Bytes

#Static Routes: 157
   Gin: 34064 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        83.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	10000000	       136 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 5000000	       333 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       158 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	20000000	       104 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	10000000	       163 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   50000	     32729 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	20000000	        82.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	20000000	       103 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	10000000	       131 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 1000000	      1476 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	        88.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	        97.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	20000000	       103 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	  500000	      2528 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  100000	     22313 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	30.647s
```

The master branch benchmark data:
```
➜  go-http-routing-benchmark git:(master) ✗ go test -bench=Gin
#GithubAPI Routes: 203
   Gin: 52064 Bytes

#GPlusAPI Routes: 13
   Gin: 3936 Bytes

#ParseAPI Routes: 26
   Gin: 6912 Bytes

#Static Routes: 157
   Gin: 30480 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        97.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	10000000	       180 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 3000000	       544 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       178 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	10000000	       124 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	10000000	       220 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   30000	     48147 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	20000000	        89.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	10000000	       149 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	10000000	       213 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 1000000	      2136 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	        94.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	10000000	       149 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	  500000	      3791 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	   50000	     29414 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	32.626s
```

**Comment by thinkerou** [comment]
About the proposal, #1390 committed by @4396 on 12 Jun 2018 first, and #1447 committed by @youngbloood on 28 Jul 2018, but they have a bit performance issue, please see https://github.com/gin-gonic/gin/pull/1390#issuecomment-491606065 and https://github.com/gin-gonic/gin/pull/1447#issuecomment-444717435.
For respecting everybody's contribution and positivity, we should handle and merge the first commit pull request, but sorry the first and second have some performance issue, maybe we should merge the pull request that the goal is the same. thanks!

**Comment by zaynetro** [comment]
I am fine with anything as long as the changes land on master.

**Comment by appleboy** [comment]
@zaynetro Could you also update the documentation?

**Comment by zaynetro** [comment]
I wasn't sure where to update the documentation so decided to extend an existing example.

**Comment by wpjunior** [comment]
Nice feature!, could you release a new version with this feature?, I wanna use it without lock with the master branch.

**Comment by Dominik-K** [comment]
@appleboy @javierprovecho Can you release this useful feature that we can properly version this module?

It fixes #748 & #1759.

**Comment by thinkerou** [comment]
@Dominik-K yes

**Comment by ltpquang** [comment]
@thinkerou nice feature, but why is it labeled `break-backward`?

**Pull request merged**
