### PR TITLE
feat(logger): ability to skip logs based on user-defined logic

### PR DESCRIPTION
**Pull request by palvaneh**
It's a backward-compatible update that let users skip logs based on customized logic.

Gin's `LoggerConfig` only allows configuring `SkipPaths`. It might not be enough when users need to skip logging based on different params like full path or status code.

### CODE REVIEW

**Comment by palvaneh** [comment]
Is there anyone to review?

**Comment by jakubno** [comment]
I want to filter specific route, which contains param `id` and with current implementation this can't be done. This solution would solve this.

**Comment by jakubno** [comment]
@thinkerou ?

**Comment by appleboy** [comment]
@palvaneh Please help to rebase the master branch. I will take it after CI passing.

**Review by appleboy — APPROVED** [review]

**Pull request merged**
