### PR TITLE
add RenderWith

### PR DESCRIPTION
**Pull request by runner-mei**
RenderWith will is not panic while render is fail.

### CODE REVIEW

**Comment by appleboy** [comment]
Please provide testing code.

**Comment by robvdl** [comment]
I know this will break backwards compatibility so isn't likely to get renamed, but shouldn't RenderWith technicall be called Render as it returns an error, and Render then called MustRender (since it panics) and that seems to be the naming convention in Go for methods that panic.

But this is the next best thing, thanks, I really needed a render method that doesn't panic.

I also had an issue that the Instance method panics rather than return an error, which was a bit annoying when I was building a custom renderer a while back, issue #678 described that.

**Comment by runner-mei** [comment]
I add test code

**Comment by robvdl** [comment]
I know I am not one of the Gin contributors so I don't really have say in this, so merge it if you want, but...

I still stand my the fact that these methods are named incorrectly, Render should become MustRender since it's panics.

RenderWith is a terrible name as it indicates you are rendering with something being passed to it, possibly a context or something. I personally would actually call RenderWith just Render, and call Render MustRender.

I would do so in v2, breaking backwards compatibility for the greater good.

**Comment by appleboy** [comment]
@javierprovecho @tboerger What do you guys think about naming?

**Comment by themartorana** [comment]
Alternatively, #952 changes `Context.Render` (and `Context.JSON`) from a panic to returning an error. It's non-breaking, although recovery deferments will become useless. Arguments for never panic-ing are myriad - especially considering broken pipes are rarely the fault of the server.

**Comment by thinkerou** [comment]
@runner-mei please re-commit the pull request to `master` branch, thanks!

**Comment by thinkerou** [comment]
```
RenderWith is a terrible nam
```
@robvdl `ShouldRender`, how?

**Comment by runner-mei** [comment]
TryRender
or
ShouldRender

**Comment by thinkerou** [comment]
ref: `ShouldBind`, I like `ShouldRender`.

**Pull request closed without merging**
