### PR TITLE
fix(engine): fix unit test

### PR DESCRIPTION
**Pull request by flc1125**
fix: https://github.com/gin-gonic/gin/actions/runs/8234650896/job/22517007644#step:5:176

### CODE REVIEW

**Comment by flc1125** [comment]
@appleboy What's going on here

**Comment by appleboy** [comment]
@flc1125 I will take a look.

**Review by appleboy — APPROVED** [review]

**Comment by flc1125** [comment]
> @flc1125 I will take a look.

Can you tell me what happened?

**Comment by appleboy** [comment]
@flc1125 I'm not sure why GitHub Action is unstable, but I just keep restarting the CI/CD flow until all statuses are successful.

**Comment by appleboy** [comment]
> Conjecture: Would it work if we ran `runtime.GC()` before the unit test?

@flc1125 not sure. Maybe we can try it out.

**Pull request merged**
