### PR TITLE
temp fix install v1.7.5 errror

### PR DESCRIPTION
**Pull request by thinkerou**
please see #2948 thanks!

### CODE REVIEW

**Comment by Bisstocuz** [comment]
Hi, there! I handled one v1.7.5 copy by myself, you can refer to it:
https://github.com/Bisstocuz/gin/commits/v1.7.5

I think it should work normally.

And at the same time, you can mark it as v1.7.6 to skip this retracting version.

**Comment by burik666** [comment]
You SHOULD retract v1.7.5 in go.mod file and release new version (v1.7.6-pre).

if `GOPROXY` is used, the broken version will be downloads from cache until you retract it.

`docker run golang:1.17`
```
$ go env
...
GOPROXY="https://proxy.golang.org,direct"
GOSUMDB="sum.golang.org"
...
$ go get github.com/gin-gonic/gin
go: downloading github.com/gin-gonic/gin v1.7.5
.....
# github.com/gin-gonic/gin
pkg/mod/github.com/gin-gonic/gin@v1.7.5/context.go:735:13: c.engine.AppEngine undefined (type *Engine has no field or method AppEngine)
pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:154:3: unknown field 'UseRawPath' in struct literal of type Engine
pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:156:3: unknown field 'UnescapePathValues' in struct literal of type Engine
pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:508:11: engine.UseRawPath undefined (type *Engine has no field or method UseRawPath)
pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:510:20: engine.UnescapePathValues undefined (type *Engine has no field or method UnescapePathValues)

$ GOPROXY="direct" go get github.com/gin-gonic/gin
go: downloading github.com/gin-gonic/gin v1.7.4
....
```

https://go.dev/ref/mod#go-mod-file-retract

Go version < 1.16 ignore `retract` directives.

**Comment by thinkerou** [comment]
Released v1.7.6 using the code of v1.7.4 version to fix the error at first, please see https://github.com/gin-gonic/gin/releases/tag/v1.7.6, thanks!

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases

**Pull request closed without merging**
