### PR TITLE
fix #752 ignore appengine os.

### LINKED ISSUE #752: IsTerminal not available on Google App Engine
A recent commit [1] brought in the use of the `terminal.IsTerminal` function. That function is not available at compile time on Google App Engine, as can be seen in the `!appengine` build tag for the file implementing it [2].

[1] https://github.com/gin-gonic/gin/commit/32cab500ecc71d2975f5699c8a65c6debb29cfbe#diff-40646a6e1108f49d452915ba3515c206
[2] https://github.com/golang/crypto/blob/master/ssh/terminal/util.go

### PR DESCRIPTION
**Pull request by appleboy**
**critical issue #752**

Please help to review.

cc @javierprovecho @tboerger 

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by tboerger** [comment]
And why do you also ignore bsd?

**Comment by javierprovecho** [comment]
@tboerger https://github.com/golang/crypto/blob/master/ssh/terminal/util.go#L5 build tags

**Comment by vermotr** [comment]
Hi,

I also use Google App Engine and I have the same issue #752 than @kujenga:
```
go-app-builder: Failed parsing input: parser: bad import "syscall" in golang.org/x/crypto/ssh/terminal/terminal.go from GOPATH
```

I have temporarily fixed it by checking out the bb159f9 commit, but can you try to fix this problem?

**Comment by javierprovecho** [comment]
@vermotr sorry, master from github and gopkg mirror is now stable at v1.1.3, with both this and #744 reverted on master. We'll keep working on this feature in develop

**Comment by vermotr** [comment]
@javierprovecho No worries, thanks a lot for the fix!

**Comment by appleboy** [comment]
@vermotr I make new PR to ignore OS Google App Engine. Please help to test again #754.

**Pull request merged**
