### PR TITLE
fix(engine): missing route params for CreateTestContext (#2778)

### PR DESCRIPTION
**Pull request by RoCry**
This PR trying to fix the issue we met, which exact same with https://github.com/gin-gonic/gin/issues/2778

If you guys have better idea to fix this, just let me know.

### CODE REVIEW

**Comment by shrike42** [comment]
Had the same problem when trying to follow the examples. 

The fix you outline would work but I think at that point especially with the need to create a separate engine to get the valid maxParam value one could just use a different approach using ServeHTTP and forget CreateTestContext.

Tests could be written as follows based on your example:

	w := httptest.NewRecorder()
	engine := New()

        // At this point add the route(s) to test
	engine.GET("/:action/:name", func(ctx *Context) {
		ctx.String(http.StatusOK, "%s %s", ctx.Param("action"), ctx.Param("name"))
	})
	
        r = http.NewRequest(http.MethodGet, "/hello/gin", nil)
	
        engine.ServeHTTP(w,r)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "hello gin", w.Body.String())

Admittedly this does not use the test context at all but I wonder if using CreateTestContext is even a good idea one could say that ServeHTTP is a better approach. Like the context method this does not start the engine.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
@RoCry Please fix the conflicts.

**Review by thinkerou — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
we will release the feature in v1.8.2

**Comment by appleboy** [comment]
https://github.com/gin-gonic/gin/releases/tag/v1.8.2

**Pull request merged**
