### PR TITLE
Exporting CreateTestContext

### LINKED ISSUE #323: Export createTestContext as a test helper
I'm trying to write tests for my controllers (using Gin, a file that groups route handlers), but I'm not being able to mock gin Contexts. Inside the [context_test.go file](https://github.com/gin-gonic/gin/blob/master/context_test.go), there's a method that does exactly that:

``` go
func createTestContext() (c *Context, w *httptest.ResponseRecorder, r *Engine) {
    w = httptest.NewRecorder()
    r = New()
    c = r.allocateContext()
    c.reset()
    c.writermem.reset(w)
    return
}
```

But it is not exported. I also cannot replicate it because `allocateContext` and Context's `engine` field are unexported too.

What do you think about creating a test-helpers module and exporting `createTestContext`?

### PR DESCRIPTION
**Pull request by danielalves**
closes #323

### CODE REVIEW

**Comment by alediaferia** [comment]
I'd push this in a submodule.

**Comment by justindag** [comment]
+1

**Comment by nazwa** [comment]
+1

**Comment by mnuma** [comment]
:+1:

**Comment by mnuma** [comment]
+1

**Comment by javierprovecho** [comment]
@alediaferia that would require to refactor some unexported methods from `gin.Engine`. We will look for it in next version, to help you better test your middlewares.

**Comment by alediaferia** [comment]
@javierprovecho This is awesome news. Thank you.

**Comment by javierprovecho** [comment]
@danielalves thank you, merged in develop (ee820830d5eda97399d1689e178b910345c05fc2)

**Comment by awishformore** [comment]
Why is this still not in master?

**Comment by danielalves** [comment]
@awishformore I was asking this myself the other day! 
@javierprovecho Is this PR going to master? (BTW, you're welcome :smile: )

**Comment by awishformore** [comment]
Honestly, I understand all the points made about testing middleware and how this is not the right approach, but I disagree with the point made in the other thread about separating the business logic from the controllers.

The controllers are the business logic. If I separate the business logic from the controllers, how will I be able to give adequate HTTP error codes in my API responses? There should be a way to create a context from a given request (not possible right now), run the handler on that context (already possible) and then extract the response from the context (already possible).

Without these three puzzle pieces, it's not possible to do proper testing on your web projects. When using the standard http library, there are no such issues. Even with this change, it will not be straight forward, which it should be.

**Pull request closed without merging**
