### PR TITLE
Add NewRelic middleware example.

### PR DESCRIPTION
**Pull request by JeremyLoy**

### CODE REVIEW

**Comment by thinkerou** [comment]
Hi @JeremyLoy thanks your contribution, can you post one usable mini example code not only doc example? thanks!

**Comment by JeremyLoy** [comment]
@thinkerou done!

**Comment by JeremyLoy** [comment]
just to clarify, I added a dependency to for the `new-relic go-agent`. because its in the example directory, this shouldn't be an additional dependency for people that just use `gin`, correct?

**Comment by JeremyLoy** [comment]
actually @thinkerou I think this PR uncovered a major issue. Now that `gin` is using `go modules`, the next release of `gin` will make consumers of `gin` download unnecessary dependencies, like `grpc, protobug, and newrelic` as they are using in the `examples` code.

I think those should be removed in the meantime. IMHO that is a release blocker. I've made issue #1566 to track this.

**Comment by thinkerou** [comment]
Hi @JeremyLoy ci error
```diff
0.15s$ make fmt-check
# get all go files and run go fmt on them
Please run 'make fmt' and commit the result:
diff -u ./examples/new_relic/main.go.orig ./examples/new_relic/main.go
--- ./examples/new_relic/main.go.orig	2018-09-23 22:39:38.009141212 +0000
+++ ./examples/new_relic/main.go	2018-09-23 22:39:38.009141212 +0000
@@ -40,4 +40,3 @@
 	})
 	router.Run()
 }
-
make: *** [fmt-check] Error 1
```

**Comment by thinkerou** [comment]
@JeremyLoy about `go module` gin still not used now, only add `go.mod` and `go.sum` file, used it now WIP status, so you not need to change them on the pr, thanks!

**Comment by thinkerou** [comment]
@JeremyLoy please fix conflict, thanks!

**Comment by JeremyLoy** [comment]
Thanks @thinkerou ! Sorry it took a while

**Pull request merged**
