### PR TITLE
check parameter in path

### PR DESCRIPTION
**Pull request by wusphinx**
Gin takes `:` and `name` as tag of parameter in path, such as `http://localhost:4123/user/:name`. If gin get the request `http://localhost:4123/user/:name`, gin will accept it, it will be better if gin respond with 400 because the format `:name` should be only used by gin clearly.

### CODE REVIEW

**Comment by lutzhorn** [comment]
What do you mean by this?

> the format :name should be only used by gin clearly.

What do you want to happen? Why?

**Comment by wusphinx** [comment]
For example, I wrote a API, the url is:`http://localhost:4123/user/:name`, and the parameter **`name`** is necessary, but someone may request the api with `http://localhost:4123/user/:name` directly, then I don't know whether he transfered  the parameter **`name`**  or not, so I think the parameter **`name`** is a common 
 string except `:name`（just the tag what I said before).

**Comment by lutzhorn** [comment]
> someone may request the api with `http://localhost:4123/user/:name` directly, then I don't know whether he transfered the parameter `name` or not

Yes, he did and the value is `:name`.

**Comment by wusphinx** [comment]
I can't agree that the value **`:name`** is what he wanted to transfer, maybe he just forgot set the parameter **`:name`**, but I still  got the request: `http://localhost:4123/user/:name`, so, as  I said before, I think the `:name` is defined as the **`tag`** for path parameter, it should not be real path parameter.

**Comment by delphinus** [comment]
I think that is too match if it uniformly forbids the use of `:name` itself because he should want to use the string `":name"` for the `:name` params...

If you want to, you should add it in the app individually. such as,

```go
func someHandler(c *gin.Context) {
  if strings.HasPrefix(c.Param("name"), ":") {
    c.AbortWithError(400, errors.New("param `name` must not has the prefix `:`.")
    return
  }

  ...

}
```

**Comment by appleboy** [comment]
agree with @delphinus

**Pull request closed without merging**
