### PR TITLE
use StringToBytes func

### PR DESCRIPTION
**Pull request by lancoLiu**
- With pull requests:
  - Open your pull request against `master`
  - Your pull request should have no more than two commits, if not you should squash them.
  - It should pass all tests in the available continuous integration systems such as GitHub Actions.
  - You should add/modify tests to cover your proposed code changes.
  - If your pull request contains a new feature, please document it on the README.

### CODE REVIEW

**Comment by zubairhassan652** [comment]
Hi @lancoLiu  i did the same changes on my local mac and run test all test are passing on my side that's why i created this [PR](https://github.com/gin-gonic/gin/pull/2822) to check will all the workflows will be passed or not.

**Comment by lancoLiu** [comment]
> Hi @lancoLiu i did the same changes on my local mac and run test all test are passing on my side that's why i created this [PR](https://github.com/gin-gonic/gin/pull/2822) to check will all the workflows will be passed or not.

**Comment by lancoLiu** [comment]
> Hi @lancoLiu i did the same changes on my local mac and run test all test are passing on my side that's why i created this [PR](https://github.com/gin-gonic/gin/pull/2822) to check will all the workflows will be passed or not.
hi @zubairhassan652 I saw that the reason for the failure was due to the timeout of the test case. I ran the test case again and found that there was no problem.

**Comment by lancoLiu** [comment]
@appleboy @thinkerou

**Review by daheige — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Review by thinkerou — APPROVED** [review]

**Pull request merged**
