### PR TITLE
feat(context): add ContextWithFallback feature flag (#3166)

### PR DESCRIPTION
**Pull request by wei840222**
due to breaking change in https://github.com/gin-gonic/gin/issues/3166

### CODE REVIEW

**Comment by appleboy** [comment]
@wei840222 From  https://github.com/gin-gonic/gin/issues/3166#issuecomment-1143570149 comment

> Add a new flag to make it backward compatible.

We can add a new flag and let the developer decide when to turn on the feature.

**Comment by wei840222** [comment]
oh I see, let me do it

**Comment by wei840222** [comment]
@appleboy 
the one more thing I wanna check
The scope of the flag should include Context.Deadline(), Context.Done(), Context.Err(), Context.Value() or only Context.Deadline(), Context.Done(), Context.Err() ?

**Comment by appleboy** [comment]
https://github.com/gin-gonic/gin/pull/2751
https://github.com/gin-gonic/gin/pull/2769

We need to review the above two PR and make it backward compatible.

**Comment by jerome-laforge** [comment]
@appleboy & @wei840222 

maybe to avoid flawky tests: 
- ensure that :8080 is always opened (as initially done into goroutine)
- request on  http://127.0.0.1:8080/ is done before launch async task with channel

you can use this:

```go
func TestGinContextCancel(t *testing.T) {
	serv := httptest.NewServer(http.HandlerFunc(func(_ http.ResponseWriter, _ *http.Request) {
		return
	}))
	defer serv.Close()

	ensureRequestIsOver := make(chan struct{})

	wg := &sync.WaitGroup{}

	r := gin.New()
	r.GET("/", func(ginctx *gin.Context) {
		wg.Add(1)

		ginctx = ginctx.Copy()

		// start async goroutine for calling serv
		go func() {
			defer wg.Done()

			<-ensureRequestIsOver // ensure request on http://127.0.0.1:8080/ is done

			req, err := http.NewRequestWithContext(ginctx, http.MethodGet, serv.URL, nil)
			if err != nil {
				panic(err)
			}

			res, err := http.DefaultClient.Do(req)
			if err != nil {
				// context is always canceled with gin v1.8.0, it is big breaking change with gin v1.7
				t.Error("context is always canceled with gin v1.8.0, it is big breaking change with gin v1.7", err)
				return
			}

			if res.StatusCode != http.StatusOK {
				log.Println("unexpected status code ", res.Status)
				return
			}
		}()
	})

	l, err := net.Listen("tcp", ":8080")
	if err != nil {
		panic(err)
	}
	go func() {
		s := &http.Server{
			Handler: r,
		}

		if err := s.Serve(l); err != nil {
			panic(err)
		}
	}()

	res, err := http.Get("http://127.0.0.1:8080/")
	if err != nil {
		panic(err)
	}

	if res.StatusCode != http.StatusOK {
		panic(err)
	}

	close(ensureRequestIsOver)

	wg.Wait()
}
```

**Comment by wei840222** [comment]
Hi @appleboy  and @jerome-laforge 
here is the version with feature for enable context with fallback (default is disable)

**Comment by jerome-laforge** [comment]
> here is the version with feature for enable context with fallback (default is disable)

Hi @wei840222,
I have just tested with `replace github.com/gin-gonic/gin v1.8.0 => github.com/wei840222/gin v1.8.1-0.20220606034057-9a0d2d27c9a7` in my go.mod. 
It works fine on my end.

**Review by appleboy — APPROVED** [review]

**Pull request merged**
