### PR TITLE
Truncate Latency precision in long running request

### LINKED ISSUE #1823: Styling breaks when request takes long
- go version: `go version go1.10.4 linux/amd64`
- gin version (or commit ref): `5acf6601170bb49a1958c055d66d54ba152dc34b`
- operating system: `elementary OS 5.0 Juno`

## Description
If a request takes long like web sockets the logging gets a bit messed up  
see the screenshot  
This request takes long because it's a web-socket

## Screenshots
Screenshot from 2019-03-22 11-55-43

### PR DESCRIPTION
**Pull request by dmarkham**
fixes #1823

### CODE REVIEW

**Comment by thinkerou** [comment]
@dmarkham my case:
```
[GIN] 2019/03/28 - 07:30:32 | 200 |  8.005575187s |             ::1 | GET      /1
[GIN] 2019/03/28 - 07:31:57 | 200 | 1m20.000219731s |             ::1 | GET      /2
```
my code:
```
	r.GET("/1", func(c *gin.Context) {
		time.Sleep(time.Duration(8)*time.Second)
		c.JSON(200, gin.H{"msg": "hi"})
	})

	r.GET("/2", func(c *gin.Context) {
		time.Sleep(time.Duration(80)*time.Second)
		c.JSON(200, gin.H{"msg": "hi"})
	})
```

**Comment by dmarkham** [comment]
> @dmarkham my case:
> 
> ```
> [GIN] 2019/03/28 - 07:30:32 | 200 |  8.005575187s |             ::1 | GET      /1
> [GIN] 2019/03/28 - 07:31:57 | 200 | 1m20.000219731s |             ::1 | GET      /2
> ```
> my code:
> 
> ```
> 	r.GET("/1", func(c *gin.Context) {
> 		time.Sleep(time.Duration(8)*time.Second)
> 		c.JSON(200, gin.H{"msg": "hi"})
> 	})
> 
> 	r.GET("/2", func(c *gin.Context) {
> 		time.Sleep(time.Duration(80)*time.Second)
> 		c.JSON(200, gin.H{"msg": "hi"})
> 	})
> ```

**Comment by dmarkham** [comment]
OK let me see what is going on here that does not look good!

**Comment by thinkerou** [comment]
@dmarkham Oh sorry, I miss some code, you are right. thanks!

**Pull request merged**
