### PR TITLE
merge tree code from httprouter

### PR DESCRIPTION
**Pull request by thinkerou**
I recently read httprouter code, and find httprouter updated some codes, I want gin should also update `tree.go`.
But this updated whether impact gin performance, I need to test later on.

please @javierprovecho @appleboy @austinheap review the merged from httprouter pull request, thanks!

- [x] performance test compare
- [x] add and update unit test case

### CODE REVIEW

**Comment by appleboy** [comment]
We should update the https://github.com/gin-gonic/go-http-routing-benchmark repo after the pr has been merged.

**Comment by thinkerou** [comment]
OK, thanks @appleboy first I post performance data compare old gin version, and update it.

**Comment by thinkerou** [comment]
I use [web-framework-benchmark](https://github.com/vishr/web-framework-benchmark) compare old version and new version, new version performance a little better.

I will use https://github.com/gin-gonic/go-http-routing-benchmark again compare.

```sh
➜  web-framework-benchmark git:(master) ✗ go test --bench=. --benchmem
goos: darwin
goarch: amd64
pkg: github.com/vishr/web-framework-benchmark
BenchmarkGinNewStatic-8      	   30000	     52666 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinNewGitHubAPI-8   	   20000	     74617 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinNewGplusAPI-8    	  300000	      4263 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinNewParseAPI-8    	  200000	      8094 ns/op	    1421 B/op	      26 allocs/op
BenchmarkGinOldStatic-8      	   30000	     55186 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinOldGitHubAPI-8   	   20000	     76590 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinOldGplusAPI-8    	  300000	      4399 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinOldParseAPI-8    	  200000	      8340 ns/op	    1421 B/op	      26 allocs/op
PASS
ok  	github.com/vishr/web-framework-benchmark	15.086s

➜  web-framework-benchmark git:(master) ✗ go test --bench=. --benchmem
goos: darwin
goarch: amd64
pkg: github.com/vishr/web-framework-benchmark
BenchmarkGinNewStatic-8      	   30000	     54921 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinNewGitHubAPI-8   	   20000	     73823 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinNewGplusAPI-8    	  300000	      4223 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinNewParseAPI-8    	  200000	      8192 ns/op	    1421 B/op	      26 allocs/op
BenchmarkGinOldStatic-8      	   30000	     55740 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinOldGitHubAPI-8   	   20000	     76673 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinOldGplusAPI-8    	  300000	      4561 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinOldParseAPI-8    	  200000	      8509 ns/op	    1421 B/op	      26 allocs/op
PASS
ok  	github.com/vishr/web-framework-benchmark	15.269s

➜  web-framework-benchmark git:(master) ✗ go test --bench=. --benchmem
goos: darwin
goarch: amd64
pkg: github.com/vishr/web-framework-benchmark
BenchmarkGinNewStatic-8      	   30000	     53096 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinNewGitHubAPI-8   	   20000	     73949 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinNewGplusAPI-8    	  300000	      4080 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinNewParseAPI-8    	  200000	      8169 ns/op	    1421 B/op	      26 allocs/op
BenchmarkGinOldStatic-8      	   30000	     54356 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinOldGitHubAPI-8   	   20000	     77451 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinOldGplusAPI-8    	  300000	      4539 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinOldParseAPI-8    	  200000	      8211 ns/op	    1421 B/op	      26 allocs/op
PASS
ok  	github.com/vishr/web-framework-benchmark	15.057s

➜  web-framework-benchmark git:(master) ✗ go test --bench=. --benchmem
goos: darwin
goarch: amd64
pkg: github.com/vishr/web-framework-benchmark
BenchmarkGinNewStatic-8      	   30000	     55189 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinNewGitHubAPI-8   	   20000	     71915 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinNewGplusAPI-8    	  300000	      4250 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinNewParseAPI-8    	  200000	      8191 ns/op	    1421 B/op	      26 allocs/op
BenchmarkGinOldStatic-8      	   30000	     56249 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinOldGitHubAPI-8   	   20000	     76769 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinOldGplusAPI-8    	  300000	      4457 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinOldParseAPI-8    	  200000	      8163 ns/op	    1421 B/op	      26 allocs/op
PASS
ok  	github.com/vishr/web-framework-benchmark	15.204s

➜  web-framework-benchmark git:(master) ✗ go test --bench=. --benchmem
goos: darwin
goarch: amd64
pkg: github.com/vishr/web-framework-benchmark
BenchmarkGinNewStatic-8      	   30000	     52571 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinNewGitHubAPI-8   	   20000	     73440 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinNewGplusAPI-8    	  300000	      4133 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinNewParseAPI-8    	  200000	      7873 ns/op	    1421 B/op	      26 allocs/op
BenchmarkGinOldStatic-8      	   30000	     56260 ns/op	    8693 B/op	     157 allocs/op
BenchmarkGinOldGitHubAPI-8   	   20000	     77832 ns/op	   10616 B/op	     203 allocs/op
BenchmarkGinOldGplusAPI-8    	  300000	      4254 ns/op	     681 B/op	      13 allocs/op
BenchmarkGinOldParseAPI-8    	  200000	      8197 ns/op	    1421 B/op	      26 allocs/op
PASS
ok  	github.com/vishr/web-framework-benchmark	14.918s

➜  web-framework-benchmark git:(master) ✗
```

**Comment by thinkerou** [comment]
I use https://github.com/julienschmidt/go-http-routing-benchmark, they are no obvious change, so I think the performance test pass.

- old version branch:

```sh
➜  go-http-routing-benchmark git:(master) go test -bench="Gin"
#GithubAPI Routes: 203
   Gin: 52672 Bytes

#GPlusAPI Routes: 13
   Gin: 3968 Bytes

#ParseAPI Routes: 26
   Gin: 6912 Bytes

#Static Routes: 157
   Gin: 30448 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        65.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	20000000	       112 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 5000000	       277 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       134 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	20000000	        83.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	10000000	       131 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   50000	     26113 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	20000000	        70.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	20000000	        83.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	20000000	       106 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 1000000	      1197 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	        67.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	        72.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	20000000	        85.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1000000	      2041 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  100000	     18319 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	28.299s
```

- new version branch:

```sh
➜  go-http-routing-benchmark git:(master) go test -bench="Gin"
#GithubAPI Routes: 203
   Gin: 52672 Bytes

#GPlusAPI Routes: 13
   Gin: 3968 Bytes

#ParseAPI Routes: 26
   Gin: 6912 Bytes

#Static Routes: 157
   Gin: 30448 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        65.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	10000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 5000000	       270 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       135 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	20000000	        82.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	10000000	       133 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   50000	     27157 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	20000000	        73.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	20000000	        82.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	20000000	       105 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 1000000	      1235 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	        66.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	        71.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	20000000	        86.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1000000	      2152 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  100000	     18602 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	27.344s
```

**Comment by appleboy** [comment]
Is new version slower than the old version?

**Comment by thinkerou** [comment]
I test many times, the result unstabitily, some items slower.
for example, I use old version test two times and the result like this:

```sh
➜  go-http-routing-benchmark git:(master) go test -bench="Gin"
#GithubAPI Routes: 203
   Gin: 52592 Bytes

#GPlusAPI Routes: 13
   Gin: 3968 Bytes

#ParseAPI Routes: 26
   Gin: 6912 Bytes

#Static Routes: 157
   Gin: 30448 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        64.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	10000000	       116 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 5000000	       281 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       143 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	20000000	        87.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	10000000	       138 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   50000	     28801 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	20000000	        66.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	20000000	        87.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 1000000	      1284 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	        70.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	        78.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	20000000	        91.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	  500000	      2293 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  100000	     20511 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	27.528s
➜  go-http-routing-benchmark git:(master)
➜  go-http-routing-benchmark git:(master)
➜  go-http-routing-benchmark git:(master) go test -bench="Gin"
#GithubAPI Routes: 203
   Gin: 52672 Bytes

#GPlusAPI Routes: 13
   Gin: 3968 Bytes

#ParseAPI Routes: 26
   Gin: 6912 Bytes

#Static Routes: 157
   Gin: 30448 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        72.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	10000000	       122 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 5000000	       355 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       162 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	20000000	       133 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	 5000000	       242 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   30000	     49339 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	10000000	       253 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	10000000	       284 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	10000000	       206 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	  300000	      3882 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	        78.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	20000000	        94.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	  500000	      2349 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  100000	     22151 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	34.042s
➜  go-http-routing-benchmark git:(master)
```

**Comment by thinkerou** [comment]
And use new version test two times result like this:

```sh
➜  go-http-routing-benchmark git:(master) go test -bench="Gin"
#GithubAPI Routes: 203
   Gin: 52672 Bytes

#GPlusAPI Routes: 13
   Gin: 3968 Bytes

#ParseAPI Routes: 26
   Gin: 6912 Bytes

#Static Routes: 157
   Gin: 30448 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        67.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	10000000	       117 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 5000000	       300 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       151 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	20000000	        91.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	10000000	       154 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   50000	     33141 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	20000000	        77.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	20000000	        97.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	10000000	       123 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 1000000	      1425 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	        79.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	        81.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	20000000	        92.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1000000	      2368 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  100000	     21204 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	29.460s
➜  go-http-routing-benchmark git:(master)
➜  go-http-routing-benchmark git:(master)
➜  go-http-routing-benchmark git:(master) go test -bench="Gin"
#GithubAPI Routes: 203
   Gin: 52592 Bytes

#GPlusAPI Routes: 13
   Gin: 3968 Bytes

#ParseAPI Routes: 26
   Gin: 6912 Bytes

#Static Routes: 157
   Gin: 30448 Bytes

goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	20000000	        71.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	20000000	       123 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 5000000	       309 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	10000000	       151 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	20000000	        94.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	10000000	       142 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   50000	     29984 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	20000000	        72.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	20000000	        92.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	10000000	       117 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 1000000	      1329 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	20000000	        73.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	20000000	        77.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	20000000	        93.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1000000	      2248 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  100000	     19522 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	29.818s
➜  go-http-routing-benchmark git:(master)
```

**Comment by appleboy** [comment]
What is different between new and old? fix some bugs or new features? I will test in my machine.

**Comment by thinkerou** [comment]
- old version: master branch
- new version: master branch + the pr

**Comment by appleboy** [comment]
I know. Just want to know this PR improve something like support Unicode in route path.

**Comment by thinkerou** [comment]
@appleboy I will close the pull request, the feature abort only add to support Unicode in route path, I think we not need it, do you think? thanks!

**Comment by appleboy** [comment]
@thinkerou OK. Maybe we need to update the benchmark data on readme. https://github.com/gin-gonic/gin/blob/master/BENCHMARKS.md

**Comment by thinkerou** [comment]
@appleboy OK, I will update the benchmark in the week.

**Comment by appleboy** [comment]
@thinkerou Thanks. Also update https://github.com/gin-gonic/go-http-routing-benchmark repo

**Comment by thinkerou** [comment]
@appleboy OK!

**Comment by thinkerou** [comment]
@appleboy Have you permission the https://github.com/gin-gonic/go-http-routing-benchmark repo? I want to update the master branch code from `julienschmidt/go-http-routing-benchmark` and push updated code, but I don't have permission.

**Comment by appleboy** [comment]
@thinkerou I don't have permission too. Maybe ask @javierprovecho in the chat room?

**Pull request closed without merging**
