### PR TITLE
remove duplicate codes in render_test.go file

### PR DESCRIPTION
**Pull request by thinkerou**
Maybe we can use the `MarshalXML` of `gin.H` for reducing duplicate codes.
BUT should it have loop ref？

### CODE REVIEW

**Comment by appleboy** [comment]
@thinkerou Please fix the conflicts.

**Comment by appleboy** [comment]
build fail. `import cycle not allowed in test`

**Comment by thinkerou** [comment]
ok, thanks @appleboy  I rebase.

**Comment by thinkerou** [comment]
Because https://github.com/gin-gonic/gin/pull/1154#issuecomment-360688697

**Pull request closed without merging**
