### PR TITLE
[WIP] Testing all packages and generate all coverage report.

### PR DESCRIPTION
**Pull request by appleboy**
reference: https://github.com/appleboy/golang-testing/blob/master/coverage.sh

Waiting https://github.com/gin-gonic/gin/pull/756 PR.

cc @javierprovecho @tboerger

### CODE REVIEW

**Comment by tboerger** [comment]
I don't understand why we need to download your script

**Comment by appleboy** [comment]
@tboerger The script support testing multiple package and convert all coverage.out into one file.

**Comment by tboerger** [comment]
Far too complex, this can be done with a tiny loop

**Comment by tboerger** [comment]
Just add this and keep the codecov.io call like before and that's it:

        for pkg in $(go list ./... | grep -v /vendor/)
        do  
          go test -cover -coverprofile $GOPATH/src/$pkg/coverage.out $pkg || exit 1
        done

**Comment by tboerger** [comment]
Just an additional note: untested, just an example.

**Comment by appleboy** [comment]
@tboerger I know. Just like my script https://github.com/appleboy/golang-testing/blob/master/coverage.sh#L98-L104

**Comment by thinkerou** [comment]
still need the pull request?

**Pull request closed without merging**
