### PR TITLE
feat: Support get value from request header.

### LINKED ISSUE #830: How to read request header
Hi Guys,

May I know how to read the request header from gin context ? It seems there is only a write header function in the document.

Thanks in advance.

### PR DESCRIPTION
**Pull request by appleboy**
fix #838 
fix #830

### CODE REVIEW

**Comment by Hokutosei** [comment]
Greetings,

is this released? I need something like this. thank you

**Comment by appleboy** [comment]
@Hokutosei You can try to use vendor tool like `govendor` to fetch source code from `develop` branch.

**Comment by Hokutosei** [comment]
@appleboy thank you, I will try it, but unfortunately we're not using `govendor`.. hopefully it'll get to release soon :)

**Comment by appleboy** [comment]
@Hokutosei You can refer https://github.com/golang/go/wiki/PackageManagementTools page.

We will set `develop` as default branch in next release.

**Comment by SlightlyCyborg** [comment]
Hey @appleboy . Why wouldn't you just make requestHeader into RequestHeader since you just passthrough the key to requestHeader() anyway. Now there are 2 function names doing the exact same thing, but with one private.

**Comment by SlightlyCyborg** [comment]
...obviously you can't do it now, since that would be a breaking change...just wondering about the design decision here.

**Pull request merged**
