### PR TITLE
Add RunFd

### PR DESCRIPTION
**Pull request by yyoshiki41**
I use gin http.Server under [circus](http://circus.readthedocs.org/en/latest/) which is a socket manager.
I need to run http.Server through a file descriptor, so implemented `RunFd` method.

When using other socket managers (e.g. [einhorn](https://stripe.com/blog/meet-einhorn)), maybe work well.
### Usage

``` go
package main

import (
    "flag"
    "github.com/yyoshiki41/gin"
)

var (
    fd = flag.Int("fd", -1, "")
)

func main() {
    flag.Parse()

    r := gin.Default()
    // Ping test
    r.GET("/ping", func(c *gin.Context) {
        c.String(200, "pong")
    })
    // Method arg is the file descriptor number(int).
    r.RunFd(*fd)
}
```

and, `circus.ini` example is below.

``` ini
[circus]
statsd = 1

[watcher:webapp]
cmd = ./main -fd $(circus.sockets.web)
numprocesses = 1
use_sockets = True

[socket:web]
host = 127.0.0.1
port = 8080
```
### Demo

``` shell
$ circusd circus.ini
2016-02-03 11:07:13 circus[46347] [INFO] Starting master on pid 46347
2016-02-03 11:07:13 circus[46347] [INFO] sockets started
2016-02-03 11:07:13 circus[46347] [INFO] Arbiter now waiting for commands
2016-02-03 11:07:13 circus[46347] [INFO] webapp started
2016-02-03 11:07:13 circus[46347] [INFO] circusd-stats started
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on fd@5
2016-02-03 11:07:13 circus[46354] [INFO] Starting the stats streamer
```

``` shell
# Ping test
$ curl localhost:8080/ping
pong

# Other terminal
[GIN] 2016/02/03 - 11:08:11 | 200 |    2.571629ms | 127.0.0.1 |   GET     /ping
```

thx :sunny:

[Review on Reviewable](https://reviewable.io/reviews/gin-gonic/gin/526)

### CODE REVIEW

**Comment by gotokatsuya** [comment]
+1

@manucorporat

**Comment by se77en** [comment]
+1

**Comment by yyoshiki41** [comment]
@manucorporat @se77en 
sorry for late reply.

Added the tests for `RunFd`.
plz, review this pr.

**Comment by thinkerou** [comment]
@yyoshiki41 please re-commit the pull request to `master` branch, thanks!

**Comment by yyoshiki41** [comment]
@thinkerou 

thanks for your reply.
Close this and reopened a new pr forked master.
https://github.com/gin-gonic/gin/pull/1609

thanks.

**Pull request closed without merging**
