### PR TITLE
Restored support of multipart/form-data

### PR DESCRIPTION
**Pull request by konjoot**

### CODE REVIEW

**Comment by manucorporat** [comment]
Form in http.Request is a complete mess.

Form = Query + PostForm + MultipartForm
PostForm = application/x-www-form-urlencoded only
MultipartForm = multipart/form-data

since PostForm and MultipartForm are mutually exclusive, they should go together.
We should provide a binding for PostForm+MultipartForm and keep the query form outside.

What do you think?

**Comment by manucorporat** [comment]
The Go Team knows it is very poorly implemented:
https://github.com/golang/go/blob/master/src/net/http/request.go#L783-L788

**Comment by manucorporat** [comment]
We do not need a different binding for multipart.
https://github.com/gin-gonic/gin/commit/af8e099dfd28614f14d6879347bd0d1f13f7b7ae

**Comment by manucorporat** [comment]
@konjoot this is the actual commit: https://github.com/gin-gonic/gin/commit/ec1ce34d32856bbaa2ae48b300c3cc9bd8455d0e

**Comment by konjoot** [comment]
@manucorporat thanks.

**Comment by manucorporat** [comment]
@konjoot gin also provides a direct way to get the form values:
```
POST /post?id=123
Body: message=Hello&topic=gin
```

```go
router.POST("/post", func(c *gin.Context) {
    id := c.Query("id") // id==123
    message := c.PostForm("message") // message==Hello
    topic := c.PostForm("topic") // topic==gin

   // do something
})
```

**Pull request merged**
