### PR TITLE
Removing $ as when you copy the command $ causes an issue in terminal.

### PR DESCRIPTION
**Pull request by chowmean**
- Readme Change: Removed the $ sign as when you copy the command it doesn't work in terminal.

### CODE REVIEW

**Comment by jincheng9** [comment]
need to be discussed. `$` is commonly used in the docs.

**Comment by chowmean** [comment]
I think $ was used to indicate shell. Next commands doesn't have this.

**Comment by Bisstocuz** [comment]
$ was used to indicate shell, and you can also remove it when you type in command.

**Comment by chowmean** [comment]
Makes sense for the shell. But when I start using it I just copied to the whole command and it didn't work the first time as I have to remove the $. Closing this as this doesn't seem relevant.

**Pull request closed without merging**
