### PR TITLE
use encode replace json marshal increase json encoder speed

### PR DESCRIPTION
**Pull request by itcloudy**
```go
func WriteJSON(w http.ResponseWriter, obj interface{}) error {
	writeContentType(w, jsonContentType)
	jsonBytes, err := json.Marshal(obj)
	if err != nil {
		return err
	}
	w.Write(jsonBytes)
	return nil
}

func WriteJSON(w http.ResponseWriter, obj interface{}) error {
	writeContentType(w, jsonContentType)
	encoder := json.NewEncoder(w)
	err := encoder.Encode(&obj)
	if err != nil {
		return err
	}
	return nil
}
```

### CODE REVIEW

**Comment by thinkerou** [comment]
@itcloudy please fix unit test error, and can you give one link or doc about compare encode with marshal? thanks!

**Comment by appleboy** [comment]
@itcloudy build fail

**Comment by lpa** [comment]
Hello, I'm sticking to Gin master revision since last week (to benefit from a dependency issue fix in master using gin + zerolog) and I agree more speed is good, but ... am I the only one shocked to have to cope with the additionnal "\n" that the use of Encode introduce or did I miss a way to remove it ? I mean it's the first time I see a framework forcing additional "\n" at the end of any JSON body data in responses (not that I've used many though ;) ) if we follow the documentation examples. I could use c.indentedJSON of c.asciiJSON but I don't want extra features, just plain JSON as I had before with c.JSON

**Comment by obashistu** [comment]
This felt like an early Xmas present. Between the disappearance of the gin/json package and a surprise newline character in my JSON payloads I really don't know which is more exciting.  

But seriously breaking changes on this project need to be much better controlled especially in minor revisions.

**Comment by jpninanjohn** [comment]
How does using encoder increase speed? If I follow the code of encode, it calls marshal() which is the same as what Marshal calls. Am I missing something here?

**Comment by AlexanderYastrebov** [comment]
> How does using encoder increase speed? If I follow the code of encode, it calls marshal() which is the same as what Marshal calls. Am I missing something here?

Marshal creates a copy https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/encoding/json/encode.go;l=167
while Encode writes internal buffer Bytes() https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/encoding/json/stream.go;l=222 to the writer

**Pull request merged**
