### PR TITLE
Add IContext

### PR DESCRIPTION
**Pull request by marcoshuck**
Hey there.
I've created this PR in order to add the **IContext** interface. The reason behind doing this is to expose the methods that Context has using an interface.

Use case:
```golang
type Input IContext

func NewInput(c *Context) Input {
	return c
}

func example(i Input) {
	i.Get() // Works out of the box.
}
```

I didn't add any tests because it doesn't need to change gin's internal behavior. I also didn't add any documentation for the same reason.

### CODE REVIEW

**Comment by thinkerou** [comment]
thanks @marcoshuck no need now, maybe you should post more details, I am closing it now.

**Comment by marcoshuck** [comment]
No problem, thank you @thinkerou.

It's an interface that has all the methods that the Context struct has. You can replace Context with IContext in the future and make gin depend on abstractions instead of a specific struct.

That gives the developer the ability to create a new type from `gin.IContext` instead of `*gin.Context` and extend the features that it has without losing the base methods (`Get()` in the example)

**Comment by appleboy** [comment]
@marcoshuck I know your point. Something like the Echo context interface:

https://github.com/labstack/echo/blob/43e32ba83d638c73a415609f26d513eda30033ee/context.go#L22

**Comment by marcoshuck** [comment]
That's certainly right. Using pointers is great, but using interfaces is safer. I'll give you an example of how I've been using interfaces in go so far:

```golang
// This is what you let the user play with
type Context interface {
    A() int
}

// This is the internal gin implementation, don't expose it to the developer
type context struct {
    a int
}

// Context initializer
func NewContext() Context {
    c := context{ a: 1234 }
    return c
}

func (c *context) A() int {
    return c.a
}
```

Right now, it envolves a lot of work to apply these changes into gin, but sometime in the near future it would be nice to consider using interfaces all over the place.

Let me know if there is anything I can help you with.

Cheers!

**Pull request closed without merging**
