### PR TITLE
 logger_test: color

### PR DESCRIPTION
**Pull request by openset**
- With pull requests:
  - Open your pull request against `master`
  - Your pull request should have no more than two commits, if not you should squash them.
  - It should pass all tests in the available continuous integrations systems such as TravisCI.
  - You should add/modify tests to cover your proposed code changes.
  - If your pull request contains a new feature, please document it on the README.

### CODE REVIEW

**Comment by thinkerou** [comment]
@openset thanks! but why change it?

**Comment by openset** [comment]
reference  #1924

**Comment by openset** [comment]
@thinkerou It's not bug。use const better, if the color value change, test file don't need modify.

**Comment by dmarkham** [comment]
I also like this nice job @openset  :+1:

**Pull request merged**
