### PR TITLE
Make CreateTestContext public without importing net/http/httptest

### PR DESCRIPTION
**Pull request by yehezkielbs**

### CODE REVIEW

**Comment by appleboy** [comment]
ＬＧＴＭ

**Comment by MRhyne1931** [comment]
I see this has made its way as far as the develop branch.  Do we we know when it will be merged to master?

**Comment by kbritton** [comment]
I'd also love to see this merged to master.  Anything I can do to help?

**Comment by appleboy** [comment]
@kbritton @MRhyne1931 We will release next version asap. Thanks.

**Comment by Deseao** [comment]
Any news on when this will be merged?

**Comment by appleboy** [comment]
@Deseao We are working on v1.2 https://github.com/gin-gonic/gin/pull/871

**Comment by appleboy** [comment]
@Deseao We already release v1.2  see: https://github.com/gin-gonic/gin/releases/tag/v1.2

**Pull request merged**
