### PR TITLE
fix: description error

### PR DESCRIPTION
**Pull request by jincheng9**
as titled.

### CODE REVIEW

**Comment by jincheng9** [comment]
@appleboy @thinkerou plz help review this PR.  I modified the description of queryCache and formCache. The original comment is confusing and has grammar errors.

**Comment by jincheng9** [comment]
@appleboy @thinkerou hi, could you please help review this PR. thanks. :)

**Review by thinkerou — APPROVED** [review]
lgtm

**Comment by jincheng9** [comment]
thanks a lot~

**Pull request merged**
