### PR TITLE
add doc.go

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by appleboy** [comment]
@thinkerou I change the base branch to `master` see https://github.com/gin-gonic/gin/blob/master/CONTRIBUTING.md

**Comment by thinkerou** [comment]
OK, thanks! I need to re-pr into master?

**Comment by appleboy** [comment]
@thinkerou NO, I already changed on this PR.

**Comment by appleboy** [comment]
Could you help to check why the travis build error?

**Comment by thinkerou** [comment]
OK.

2017-07-04 10:55 GMT+08:00 Bo-Yi Wu <notifications@github.com>:

**Comment by easonlin404** [comment]
@appleboy  I have found sometimes travis will build error becasue `TestDebugPrintLoadTemplate` , but I don't have any ideal why caused:
```
-- FAIL: TestDebugPrintLoadTemplate (0.00s)
	Error Trace:	debug_test.go:77
	Error:		Not equal: 
			expected: "[GIN-debug] Loaded HTML Templates (2): \n\t- hello.tmpl\n\t- \n\n"
			received: "[GIN-debug] Loaded HTML Templates (2): \n\t- \n\t- hello.tmpl\n\n"
```

 maybe I can adjust using `assert.Regexp` instead of `assert.Equal`.

**Pull request merged**
