### PR TITLE
Add set samesite in cookie.

### LINKED ISSUE #2299: breaking change to v1.6.0 is inappropriate
https://github.com/gin-gonic/gin/pull/1615 is a breaking change

and it is released to v1.6.0

but for go version style, it is should be released to v2.0.0 and change `go.mod` to `github.com/gin-gonic/gin/v2` (and the package name is `gin` )

please revert https://github.com/gin-gonic/gin/pull/1615 and put the `SameSite` param to v2.0.0 

thanks.

### PR DESCRIPTION
**Pull request by appleboy**
fixed #2299

### CODE REVIEW

**Comment by wangzz719** [comment]
In this pr, SameSite property belongs to the whole gin.Context. What should I do when samesite and none samesite cookie need to set in the same gin.Context ?

**Comment by appleboy** [comment]
```go
// first cookie
c.SetSameSite(...)
c.SetCookie(...)
// second cookie
c.SetSameSite(...)
c.SetCookie(...)
```

**Comment by wangzz719** [comment]
In my opinion，SameSite belongs to a cookie，not gin.Context，why not provide a method like `c.SetSameSiteCookie` which need SameSite in parameters?

**Comment by wangzz719** [comment]
> In my opinion，SameSite belongs to a cookie，not gin.Context，why not provide a method like `c.SetSameSiteCookie` which need SameSite in parameters?

@appleboy would you plan to offer a new method with SameSite in parameters?

**Pull request merged**
