### PR TITLE
Add err != nil badge count in README

### PR DESCRIPTION
**Pull request by cpl**
The badge uses a service I developed to provide the number of err checks in the code. It provides no real value, it has no practical use.

### CODE REVIEW

**Comment by thinkerou** [comment]
display:
image

**Comment by appleboy** [comment]
https://errnil.cpl.li

This is not stable service.

**Comment by cpl** [comment]
I’ll have a look at this. I enabled full TLS in Cloudflare and this isn’t serving a cert.

**Comment by appleboy** [comment]
Please reopen the PR if the service is stable.

**Pull request closed without merging**
