### PR TITLE
ClientIP() fix for single item in X-Forwarded-For.

### PR DESCRIPTION
**Pull request by jarm**

### CODE REVIEW

**Comment by manucorporat** [comment]
@jarm I am not sure what you are trying to fix... but now it does not pass the unit tests:
```
--- FAIL: TestContextClientIP (0.00s)
	Location:	context_test.go:411
	Error:		Not equal: "30.30.30.30" (expected)
			        != "20.20.20.20" (actual)
		
	Location:	context_test.go:413
	Error:		Not equal: "40.40.40.40" (expected)
			        != "30.30.30.30" (actual)
```

**Comment by manucorporat** [comment]
I can not merge this since I don't know what you are trying to fix.

**Comment by jarm** [comment]
The issue I'm trying to fix is that sometimes X-Forwarded-For contains a single ip address.

**Comment by manucorporat** [comment]
@jarm are you sure that it didn't work without your fix? I just tried and it works.

**Comment by jarm** [comment]
You're absolutely right.

**Comment by manucorporat** [comment]
I just added a new test with a single IP and it passes without your fix:
https://travis-ci.org/gin-gonic/gin/builds/63850825
https://github.com/gin-gonic/gin/commit/80d3cc6b7512e487bcf58daf497e6b5206216818

**Comment by manucorporat** [comment]
Anyway, thanks for your report! the unit tests didn't covered that use case, if fact I have reviewed the ClientIP() logic and I found another bug, we should trim the white spaces always.

**Comment by manucorporat** [comment]
@jarm fixed: https://github.com/gin-gonic/gin/commit/0a9030f9d7a42372f8fae1381e3af62db9b9b289

**Pull request closed without merging**
