### PR TITLE
Exporting routesInterface

### PR DESCRIPTION
**Pull request by WnP**
I like working with modules, with [routesInterface](https://github.com/gin-gonic/gin/blob/master/routergroup.go#L14) exported we can construct function that set routes for a give group or directly for the engine

### CODE REVIEW

**Comment by konjoot** [comment]
+1, and with that done, we will have an ability, to mock gin.Engine and gin.RouterGroup in our tests.

**Comment by manucorporat** [comment]
ok, I think it makes sense

**Comment by manucorporat** [comment]
@WnP @konjoot merged!

**Comment by manucorporat** [comment]
The interface does not include `Group()`. is that ok?

**Comment by konjoot** [comment]
ok, for me, and thank you for merge.

**Comment by manucorporat** [comment]
@konjoot  ok, anyway I fixed it:  https://github.com/gin-gonic/gin/commit/9e4407975621702acda5bf585dce03f368a88070

**Comment by WnP** [comment]
thanks

**Pull request merged**
