### PR TITLE
Adjust Render.Redirect test case

### PR DESCRIPTION
**Pull request by yinggaozhen**
- Fixed : Adjust the correct test case, the source code is to `pinic`,  but test case is not correctly captured
- Add : Add the test case of code 201

### CODE REVIEW

**Comment by thinkerou** [comment]
@appleboy I can't merge the pr, please merge it, thanks!

**Comment by appleboy** [comment]
@thinkerou I also can't merge the PR.

**Comment by yinggaozhen** [comment]
@appleboy @thinkerou 

I'm really sorry, this is a mistake, I deleted the repo :joy:. I submitted a new pull request [#2053](#2053) again.  I hope you can help to review it again. thank you very much.

**Comment by thinkerou** [comment]
@yinggaozhen thanks! merged.

**Pull request closed without merging**
