### PR TITLE
right-justified benchmarks data

### PR DESCRIPTION
**Pull request by thinkerou**
Right-justified benchmarks data for reading.

### CODE REVIEW

**Comment by appleboy** [comment]
maybe we should update the benchmarks data. cc @javierprovecho

**Comment by thinkerou** [comment]
Hi, @appleboy you mean that we should re-run benchmarks, right?

**Comment by appleboy** [comment]
@thinkerou Yes. the benchmarks data is too old.

**Comment by appleboy** [comment]
I will test the benchmark using DigitalOcean machine

CPU: 4
OS: Ubuntu 16.04.2 x64
Memory: 8 GB Memory

screen shot 2017-07-19 at 9 52 09 am

**Comment by appleboy** [comment]
@thinkerou @javierprovecho 

See new PR: https://github.com/gin-gonic/gin/pull/1035

**Comment by thinkerou** [comment]
OK, @appleboy Thanks!

**Pull request closed without merging**
