### PR TITLE
avoid 'multiple response.WriteHeader calls' error

### PR DESCRIPTION
**Pull request by alicebob**

### CODE REVIEW

**Comment by alicebob** [comment]
The unittest fixes are a bit unclean, but they seemed broken to me.

**Comment by thinkerou** [comment]
@alicebob please re-commit the pull request to `master` branch, thanks!

**Comment by alicebob** [comment]
@thinkerou : sometime since opening this PR in 2016 I removed my clone of the repo, and I don't have the code anymore.
It does seems like an easy fix if it's still relevant, but I polity suggest someone who is an active user of Gin to recreate the PR. :(

**Comment by thinkerou** [comment]
@alicebob OK, thanks!

**Pull request closed without merging**
