### PR TITLE
add protobuf binding for gin

### PR DESCRIPTION
**Pull request by zhing**
We use gin as the server of our mobile app, choosing protobuf to Serialize our data for known reasons. So I add a module for protobuf binding. But I'm sorry to say we can not use 'binding:"len<10"' to validate on protobuf util now, this is what I'm doing on.

### CODE REVIEW

**Comment by SlinSo** [comment]
I think you should change the mime type to a protobuf specific type.

most used types seem to be:
application/x-protobuf
application/protobuf

see https://issues.apache.org/jira/browse/HBASE-7472

**Comment by zhing** [comment]
I'll have a try

**Comment by zhing** [comment]
when I change the mime type to "application/x-protobuf"，the pull request build failed with go1.4.2. But It works well on my machine with go1.4.2, Why?

**Comment by javierprovecho** [comment]
@zhing don't worry, ci failed because of a bad test behaviour.

**Comment by javierprovecho** [comment]
@zhing thank you, merged in develop (91231d4801efb0db28cd21a4e7cd6e980a2183c8)

**Pull request closed without merging**
