### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by llgoer**
change  `ShouldBindXML` to `ShouldBindJSON`

### CODE REVIEW

**Comment by thinkerou** [comment]
I don't know why go master branch error, I see later.

**Comment by syssam** [comment]
@thinkerou it is my typing mistake.

**Comment by thinkerou** [comment]
@syssam what's mean?

**Comment by chainhelen** [comment]
@thinkerou He say [this](https://github.com/gin-gonic/gin/pull/1485/files#diff-04c6e90faac2675aa89e2176d2eec7d8R560)   #1485

**Comment by thinkerou** [comment]
@chainhelen thanks!
go master branch error, maybe because `url.Values` change, but I need to check some time.
go 1.10.x OK, print `c.Request.URL.Query()` log:

```go
url.Values{"ids[a]":[]string{"hi"}, "ids[b]":[]string{"3.14"}, "both":[]string{"GET"}, "id":[]string{"main", "omit"}, "array[]":[]string{"first", "second"}}
```

go master error, print `c.Request.URL.Query()` log:

```go
url.Values{"both=GET&id=main&id=omit&array[]=first&array[]=second&ids[a]=hi&ids[b]=3.14":[]string{""}}
```

**Pull request merged**
