### PR TITLE
Don't log requests

### LINKED ISSUE #1331: Recovery middleware leaks sensitive cookies, tokens, and headers into logs
Session cookies, API tokens, and authorization headers are all being leaked. The request is dumped if a handler hits a panic when using the recovery middleware: https://github.com/gin-gonic/gin/blob/65a65c2edd4e86f96634a553f07a25c38f2b1c75/recovery.go#L41

This is very insecure default behavior, and there appears to be no way to opt out other than not using the middleware.

### PR DESCRIPTION
**Pull request by dustin-decker**
Fixes #1331

HTTP logging leaks sensitive request information.

This PR removes HTTP request logging during panics.

### CODE REVIEW

**Comment by chainhelen** [comment]
@dustin-decker You should ensure `make test`  for passing citest first.

**Comment by dustin-decker** [comment]
@chainhelen Thanks for the notification. Indeed, but I didn't expect there to be a test inspecting the output buffer for a HTTP header!

**Comment by AgrimPrasad** [comment]
@dustin-decker @javierprovecho @thinkerou

Could we proceed with this one? We'd also like to prevent sensitive user information from being exposed in gin panic logs on our servers.

If there are any holdups (I see test failing + unresolved conflicts) I would be glad to fix these issues myself if the author is unavailable.

**Comment by thinkerou** [comment]
@dustin-decker please fix conflict, thanks!

**Comment by appleboy** [comment]
maybe we can remove the httpdump request data in `Release` mode and keep the log in `debug` mode.

**Comment by dustin-decker** [comment]
Thanks for reviewing, @appleboy.
Added printing httpdump request data when debug mode is enabled (and tested it).

**Comment by appleboy** [comment]
@thinkerou Need your approval :)

**Pull request merged**
