### PR TITLE
Use camel case instead of ALL_CAPS

### PR DESCRIPTION
**Pull request by crispgm**
ENV_GIN_MODE -> EnvGinMode

### CODE REVIEW

**Comment by thinkerou** [comment]
it will break forward compatibility.

**Comment by crispgm** [comment]
@thinkerou well, should I close?

**Comment by thinkerou** [comment]
@crispgm sorry, I understand error, it not break, because set environment var using `GIN_MODE`, so not close, need cr, thanks!

**Comment by thinkerou** [comment]
@crispgm maybe we should use `ALL_CAPS` for `const`, https://github.com/Unknwon/go-code-convention/blob/master/en-US/naming_rules.md#constants, but I not find the official document.

**Comment by crispgm** [comment]
@thinkerou Nope, mixed caps is the common practice for constants, which is used by go linters.
See <https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps>.

**Pull request merged**
