### PR TITLE
add package for govendor

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by appleboy** [comment]
Why add packages?

**Comment by thinkerou** [comment]
Hi, @appleboy I found all pr failed recently on `go master` branch, [error info](https://travis-ci.org/gin-gonic/gin/jobs/300520157):
```
0.22s$ make vet
go vet github.com/gin-gonic/gin github.com/gin-gonic/gin/binding github.com/gin-gonic/gin/binding/example github.com/gin-gonic/gin/examples/app-engine github.com/gin-gonic/gin/examples/auto-tls github.com/gin-gonic/gin/examples/basic github.com/gin-gonic/gin/examples/custom-validation github.com/gin-gonic/gin/examples/favicon github.com/gin-gonic/gin/examples/graceful-shutdown/close github.com/gin-gonic/gin/examples/graceful-shutdown/graceful-shutdown github.com/gin-gonic/gin/examples/http2 github.com/gin-gonic/gin/examples/multiple-service github.com/gin-gonic/gin/examples/realtime-advanced github.com/gin-gonic/gin/examples/realtime-chat github.com/gin-gonic/gin/examples/template github.com/gin-gonic/gin/examples/upload-file/multiple github.com/gin-gonic/gin/examples/upload-file/single github.com/gin-gonic/gin/ginS github.com/gin-gonic/gin/json github.com/gin-gonic/gin/render
examples/favicon/main.go:5:2: cannot find package "github.com/thinkerou/favicon" in any of:
	/home/travis/gopath/src/github.com/gin-gonic/gin/vendor/github.com/thinkerou/favicon (vendor tree)
	/home/travis/.gimme/versions/go/src/github.com/thinkerou/favicon (from $GOROOT)
	/home/travis/gopath/src/github.com/thinkerou/favicon (from $GOPATH)
examples/multiple-service/main.go:9:2: cannot find package "golang.org/x/sync/errgroup" in any of:
	/home/travis/gopath/src/github.com/gin-gonic/gin/vendor/golang.org/x/sync/errgroup (vendor tree)
	/home/travis/.gimme/versions/go/src/golang.org/x/sync/errgroup (from $GOROOT)
	/home/travis/gopath/src/golang.org/x/sync/errgroup (from $GOPATH)
make: *** [vet] Error 1
``` 
so, I attempt to fix it, thanks.

**Comment by appleboy** [comment]
We don't need import package in examples folder.

* examples/favicon/main.go:	"github.com/thinkerou/favicon"
* examples/multiple-service/main.go:	"golang.org/x/sync/errgroup"

**Comment by appleboy** [comment]
@thinkerou Let me check `make vet` command. It always builds fail in the latest version of golang.

**Comment by appleboy** [comment]
@thinkerou I fixed in your branch.

**Comment by thinkerou** [comment]
@appleboy OK, thanks.

**Pull request merged**
