### PR TITLE
The url.RawPath used when engine.UseRawPath is set to true.

### PR DESCRIPTION
**Pull request by egorse**
Fix for #777, #640, #722.

Another try to make it faster into master :) 
Almost same as #777  but handles one more case in tree.getValue.

@appleboy Please review it. With this (plus forcing UseRawPath) the drone became handling escaped params. Thanks!

### CODE REVIEW

**Comment by egorse** [comment]
Should be 1.4 build fixed?
The 1.7.4 test failed probably due some high load at travis (the sleep in code I did not touch seems was not big enough:S)

**Comment by appleboy** [comment]
Please see the [contributing guide](https://github.com/gin-gonic/gin#contributing) before making new pull request.

> Open your pull request against `develop`

**Comment by appleboy** [comment]
I change the base branch to `develop`. Please fix the conflicts. @egorse

**Comment by appleboy** [comment]
@egorse Duplicated of #777. I think we need to discuss in #777 first. You can make another PR after merged #777

**Comment by appleboy** [comment]
@egorse Please help to fix the conflicts.

**Comment by appleboy** [comment]
Nothing changes?

**Comment by egorse** [comment]
@appleboy how about now? 

The go1.4 still should not works as has no url.RawPath. Should go1.4 be supported? Could be ugly to fix but possible.

**Comment by appleboy** [comment]
I think we can drop golang 1.4 and 1.5 support. cc @tboerger @javierprovecho What do you think?

**Comment by appleboy** [comment]
@egorse We don't need to support 1.4, 1.5 in develop branch. You can rebase your code base on latest develop branch. https://github.com/gin-gonic/gin/blob/develop/.travis.yml#L4-L7

**Comment by appleboy** [comment]
@egorse Open your pull request against `develop`  not `master`

**Comment by egorse** [comment]
#810 made

**Pull request closed without merging**
