### PR TITLE
add notify accept signal

### PR DESCRIPTION
**Pull request by awkj**
- With pull requests:
  - Open your pull request against `master`
  - Your pull request should have no more than two commits, if not you should squash them.
  - It should pass all tests in the available continuous integrations systems such as TravisCI.
  - You should add/modify tests to cover your proposed code changes.
  - If your pull request contains a new feature, please document it on the README.

Add a example

kill command will default send syscall.SIGTERM, add it in example will friendly to gin user.

### CODE REVIEW

**Comment by thinkerou** [comment]
@awkj also need to update readme

error info:
```
0.14s$ make embedmd
embedmd -d *.md
@@ -1660,7 +1660,10 @@
 	// Wait for interrupt signal to gracefully shutdown the server with
 	// a timeout of 5 seconds.
 	quit := make(chan os.Signal)
-	signal.Notify(quit, os.Interrupt)
+	// kill (no param) default send syscanll.SIGTERM
+	// kill -2 is syscall.SIGINT
+	// kill -9 is syscall. SIGKILL but can"t be catch
+	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
 	<-quit
 	log.Println("Shutdown Server ...")
 
make: *** [embedmd] Error 2
The command "make embedmd" exited with 2.
```

**Comment by awkj** [comment]
I should add readme.md to this folder?

**Comment by thinkerou** [comment]
@awkj no, you should update readme.md file which makes it the same as `server.go`.

**Comment by awkj** [comment]
> @awkj no, you should update readme.md file which makes it the same as `server.go`. update the part: https://github.com/gin-gonic/gin#graceful-restart-or-stop

thanks reply, I already add it to README.md

**Pull request merged**
