### PR TITLE
chore: Switch from govendor to dep

### PR DESCRIPTION
**Pull request by sudo-suhas**
`dep` is slated to be the official Go dependency management tool. It is ready for production use. This PR switches from `govendor` to `dep`. I also renamed the `examples` folders to `_examples` so that the dependencies are not pulled in by `dep`.

Packages used by examples removed from vendor:
- github.com/dustin/go-broadcast
- github.com/gin-gonic/autotls
- github.com/manucorporat/stats
- github.com/thinkerou/favicon
- golang.org/x/crypto/acme/autocert
- golang.org/x/sync/errgroup

Almost all other dependency revisions were changed to more recent commits:

| pkg | Old | New |
|-----|-----|-----|
| github.com/golang/protobuf | [5a0f697c](https://github.com/golang/protobuf/commit/5a0f697c9ed9d68fef0116532c6e05cfeae00e55) | [130e6b02](https://github.com/golang/protobuf/commit/130e6b02ab059e7b717a096f397c5b60111cae74) |
| github.com/json-iterator/go | [36b14963](https://github.com/json-iterator/go/commit/36b14963da70d11297d313183d7e6388c8510e1e) | [6240e1e7](https://github.com/json-iterator/go/commit/6240e1e7983a85228f7fd9c3e1b6932d46ec58e2) (`v1.0.3`) |
| github.com/mattn/go-isatty | [57fdcb98](https://github.com/mattn/go-isatty/commit/57fdcb988a5c543893cc61bce354a6e24ab70022) | [0360b2af](https://github.com/mattn/go-isatty/commit/0360b2af4f38e8d38c7fce2a9f4e702702d73a39) (`v0.0.3`) |
| github.com/stretchr/testify | [976c720a](https://github.com/stretchr/testify/commit/976c720a22c8eb4eb6a0b4348ad85ad12491a506) | [69483b4b](https://github.com/stretchr/testify/commit/69483b4bd14f5845b5a1e55bca19e954e827f1d0) (`v1.1.4`) |
| github.com/ugorji/go | [c88ee250](https://github.com/ugorji/go/commit/c88ee250d0221a57af388746f5cf03768c21d6e2) | [f76f59a9](https://github.com/ugorji/go/commit/f76f59a92f8224c695c0e2c401b9ad17e820a8f5) |
| golang.org/x/net/context | [d4c55e66](https://github.com/golang/net/commit/d4c55e66d8c3a2f3382d264b08e3e3454a66355a) (`release-branch.go1.7`) | [a04bdaca](https://github.com/golang/net/commit/a04bdaca5b32abe1c069418fb7088ae607de5bd0) |
| gopkg.in/go-playground/validator.v8 | [5f57d222](https://github.com/go-playground/validator/commit/5f57d2222ad794d0dffb07e664ea05e2ee07d60c) (`v8.18.1`) | [5f1438d3](https://github.com/go-playground/validator/commit/5f1438d3fca68893a817e4a66806cea46a9e4ebf) (`v8.18.2`) |
| gopkg.in/yaml.v2 | [a5b47d31](https://github.com/go-yaml/yaml/commit/a5b47d31c556af34a302ce5d659e6fea44d90de0) | [eb3733d1](https://github.com/go-yaml/yaml/commit/eb3733d160e74a9c7e442f435eb3bea458e1d19f) |

**Note:** The revision was not changed for the package `github.com/gin-contrib/sse`.

### CODE REVIEW

**Comment by appleboy** [comment]
@javierprovecho @tboerger Please help to review this.

**Comment by douglarek** [comment]
Maybe we should wait for vgo: https://research.swtch.com/vgo

**Comment by carllhw** [comment]
Any progress ?

**Comment by hellupline** [comment]
aditional info: vgo required semver tag to contain levels of version, the current 1.2 does not check in vgo
it should be at least 1.2.0

currently vgo will only match with 1.1.4

**Comment by yushine** [comment]
Any progress ?
@sudo-suhas

**Comment by sudo-suhas** [comment]
Closing this PR as it is very much out of date and there is no indication that this would be accepted.

**Comment by thinkerou** [comment]
@sudo-suhas thank you work, I think we may use vgo later on.

**Comment by thinkerou** [comment]
ref #1569

**Pull request closed without merging**
