### PR TITLE
Support custom json codec at runtime

### PR DESCRIPTION
**Pull request by timandy**
Extract out an interface `api.JsonApi` to restrict all serialization and deserialization behaviors. 

Developers only need to implement this interface and cover `json.API` value can realize custom json codec.

In the future, we can define `api.XmlApi` in the same way.

Solved #3217

### CODE REVIEW

**Comment by timandy** [comment]
@thinkerou LTAL, thks.

**Comment by timandy** [comment]
@thinkerou  Could you make a code review for this PR. Thanks  a lot.

**Comment by timandy** [comment]
@thinkerou @appleboy  Please make a code review, thanks. We really need this feature in our project.

**Comment by thinkerou** [comment]
please also update readme, and add example code, thanks

**Comment by timandy** [comment]
> please also update readme, and add example code, thanks

@thinkerou 
I extract out an interface `api.JsonApi` to restrict all serialization and deserialization behaviors. 
Developers only need to implement this interface and cover` json.API` value can realize custom json codec.

And I also add examples in readme.

PTAL, thanks.

**Comment by timandy** [comment]
@thinkerou

**Comment by timandy** [comment]
@appleboy PLTA, thanks very much.

**Comment by timandy** [comment]
@thinkerou In the previous force push, I fixed the format of the example in the readme file.

**Comment by timandy** [comment]
Any progress?

**Comment by timandy** [comment]
@thinkerou  Please table a look

**Pull request closed without merging**
