### PR TITLE
Write status code in external writer too

### PR DESCRIPTION
**Pull request by marvell**

### CODE REVIEW

**Comment by HeyImAlex** [comment]
Are you wrapping the ResponseWriter with your own? Because I'm pretty sure Context.Writer and Context.writermem are the same object, one is just wrapped up in an interface.

**Comment by mvader** [comment]
@heyimalex but if you change the `Context.Writer`, which is possible and middlewares like gin cache do, `Context.writermem` is not changed. And some things are only written in the private one, like the status https://github.com/gin-gonic/gin/blob/master/context.go#L378-L380

**Comment by heyimalex** [comment]
If you change Context.Writer, don't you need to wrap the old one? If you wanted the wrapping-writers to get the status, then this method should *only* call Context.Writer.WriteHeader and not the one on writermem.

**Comment by willnewrelic** [comment]
I'm with @heyimalex .  Shouldn't this function simply be:

```go
func (c *Context) Status(code int) {
	c.Writer.WriteHeader(code)
}
```

**Comment by periclesroo** [comment]
Hey, any updates on this one?

**Comment by thinkerou** [comment]
@marvell please re-commit the pull request to `master` branch, thanks!

**Comment by willnewrelic** [comment]
@thinkerou @heyimalex @marvell 

I have opened a new PR against latest `master` with this change fixed:

https://github.com/gin-gonic/gin/pull/1606

**Pull request closed without merging**
