### PR TITLE
add querystring parameter example to readme

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by manucorporat** [comment]
Since reading the query and post form are very common use cases. Gin v1. provides a shortcut for that:
```go
c.Query(key)// --> returns the URL query
c.PostForm(key) //--> return the urlencoded query in body
c.Param(key)// --> shortcut for c.Params.ByName(key)
```

https://github.com/gin-gonic/gin/blob/master/context.go#L193-L223

**Comment by manucorporat** [comment]
Your example could be rewritten as:

```go
func main() {
	r := gin.Default()
	
	// Query string parameters are parsed using the existing underlying request object.  
	// The request responds to a url matching:  /search?firstname=Jane&lastname=Doe
	r.GET("/search", func(c *gin.Context) {
		firstname := c.DefaultQuery("firstname", "Guest")
		lastname := c.Query("lastname") // shortcut for c.Request.URL.Query().Get("lastname")
		message := "Hello " + firstname + lastname
		c.String(http.StatusOK, message)
	})
	r.Run(":8080")
}
```

**Comment by JustinBeckwith** [comment]
Thanks!  This will probably save a few others from making the same mistake :)

**Comment by JustinBeckwith** [comment]
Actually wait - I don't see a Query method on the Context object?
https://godoc.org/github.com/gin-gonic/gin#Context

**Comment by manucorporat** [comment]
@JustinBeckwith https://godoc.org/github.com/gin-gonic/gin#Context.Query

**Comment by manucorporat** [comment]
@JustinBeckwith we just released v1.0rc1 a days ago. https://github.com/gin-gonic/gin/releases/tag/v1.0rc1

it features many new apis and improvements, but probably the most important thing: the api is frozen.

**Pull request merged**
