### PR TITLE
chore(docs): Bump to v1.7.7

### PR DESCRIPTION
**Pull request by Bisstocuz**
This is an optional solution for v1.7.5 released mistakenly. I think skip v1.7.5 is the best solution.

See: https://github.com/gin-gonic/gin/pull/2951#issuecomment-975146109

@thinkerou 
As your approval, you can create a new release refer to [the list](https://github.com/Bisstocuz/gin/commits/v1.7.6), and merge this PR then put this commit into the new release.

### CODE REVIEW

**Comment by thinkerou** [comment]
https://github.com/gin-gonic/gin/commits/release_176
run `make test` on my mac:
```
=== RUN   TestTreeRunDynamicRouting
2021/11/23 11:21:18 http: panic serving 127.0.0.1:59863: runtime error: slice bounds out of range [:8] with capacity 7
goroutine 729 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:1801 +0xb9
panic({0x158bca0, 0xc0002f44b0})
	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1047 +0x266
github.com/gin-gonic/gin.(*node).getValue(0xc0006be810, {0xc0002ee124, 0x203000}, 0xc00000e1e0, 0xc00000e468, 0x0)
	/Users/tianou/gin/tree.go:431 +0x1345
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001a24e0, 0xc000120200)
	/Users/tianou/gin/gin.go:548 +0x1ee
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001a24e0, {0x168f730, 0xc00033cb60}, 0xc000121500)
	/Users/tianou/gin/gin.go:511 +0x1d6
net/http.serverHandler.ServeHTTP({0xc0006be720}, {0x168f730, 0xc00033cb60}, 0xc000121500)
	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc000543040, {0x1694360, 0xc00074a060})
	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:3033 +0x4e8
    gin_integration_test.go:42:
        	Error Trace:	gin_integration_test.go:42
        	            				gin_integration_test.go:491
        	Error:      	Received unexpected error:
        	            	Get "http://127.0.0.1:59819/something/abcdad/thirdthing": EOF
        	Test:       	TestTreeRunDynamicRouting
--- FAIL: TestTreeRunDynamicRouting (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14abebf]

goroutine 498 [running]:
testing.tRunner.func1.2({0x153d800, 0x19ff090})
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1212 +0x218
panic({0x153d800, 0x19ff090})
	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1038 +0x215
github.com/gin-gonic/gin.testRequest(0xc0001a2340, {0xc000363f28, 0x3, 0x15ca61d})
	/Users/tianou/gin/gin_integration_test.go:43 +0x17f
github.com/gin-gonic/gin.TestTreeRunDynamicRouting(0xc0005d4d00)
	/Users/tianou/gin/gin_integration_test.go:491 +0x2573
testing.tRunner(0xc0001a2340, 0x15e9b10)
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1306 +0x35a
FAIL	github.com/gin-gonic/gin	0.730s
FAIL
make: *** [test] Error 1
```

**Comment by Bisstocuz** [comment]
> https://github.com/gin-gonic/gin/commits/release_176 run `make test` on my mac:
> 
> ```
> === RUN   TestTreeRunDynamicRouting
> 2021/11/23 11:21:18 http: panic serving 127.0.0.1:59863: runtime error: slice bounds out of range [:8] with capacity 7
> goroutine 729 [running]:
> net/http.(*conn).serve.func1()
> 	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:1801 +0xb9
> panic({0x158bca0, 0xc0002f44b0})
> 	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1047 +0x266
> github.com/gin-gonic/gin.(*node).getValue(0xc0006be810, {0xc0002ee124, 0x203000}, 0xc00000e1e0, 0xc00000e468, 0x0)
> 	/Users/tianou/gin/tree.go:431 +0x1345
> github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001a24e0, 0xc000120200)
> 	/Users/tianou/gin/gin.go:548 +0x1ee
> github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001a24e0, {0x168f730, 0xc00033cb60}, 0xc000121500)
> 	/Users/tianou/gin/gin.go:511 +0x1d6
> net/http.serverHandler.ServeHTTP({0xc0006be720}, {0x168f730, 0xc00033cb60}, 0xc000121500)
> 	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:2878 +0x43b
> net/http.(*conn).serve(0xc000543040, {0x1694360, 0xc00074a060})
> 	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:1929 +0xb08
> created by net/http.(*Server).Serve
> 	/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:3033 +0x4e8
>     gin_integration_test.go:42:
>         	Error Trace:	gin_integration_test.go:42
>         	            				gin_integration_test.go:491
>         	Error:      	Received unexpected error:
>         	            	Get "http://127.0.0.1:59819/something/abcdad/thirdthing": EOF
>         	Test:       	TestTreeRunDynamicRouting
> --- FAIL: TestTreeRunDynamicRouting (0.01s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14abebf]
> 
> goroutine 498 [running]:
> testing.tRunner.func1.2({0x153d800, 0x19ff090})
> 	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1209 +0x24e
> testing.tRunner.func1()
> 	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1212 +0x218
> panic({0x153d800, 0x19ff090})
> 	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1038 +0x215
> github.com/gin-gonic/gin.testRequest(0xc0001a2340, {0xc000363f28, 0x3, 0x15ca61d})
> 	/Users/tianou/gin/gin_integration_test.go:43 +0x17f
> github.com/gin-gonic/gin.TestTreeRunDynamicRouting(0xc0005d4d00)
> 	/Users/tianou/gin/gin_integration_test.go:491 +0x2573
> testing.tRunner(0xc0001a2340, 0x15e9b10)
> 	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1259 +0x102
> created by testing.(*T).Run
> 	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1306 +0x35a
> FAIL	github.com/gin-gonic/gin	0.730s
> FAIL
> make: *** [test] Error 1
> ```
env: `go version go1.17.3 linux/amd64`
I tested your branch and I got the same error,
but I got PASS on my https://github.com/Bisstocuz/gin/commits/v1.7.6:
```bash
# go test
go: downloading github.com/ugorji/go v1.1.7
go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/go-playground/universal-translator v0.17.0
go: downloading github.com/leodido/go-urn v1.2.0
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/go-playground/locales v0.13.0
2021/11/23 11:56:44 The AppEngine flag is going to be deprecated. Please check issues #2723 and #2739 and use 'TrustedPlatform: gin.PlatformGoogleAppEngine' instead.
[GIN] 2021/11/23 - 11:56:44 | 200 |        6.23µs |       192.0.2.1 | GET      "/name1/api"
[GIN] 2021/11/23 - 11:56:44 | 200 |       1.312µs |       192.0.2.1 | GET      "/name2/api"
[GIN] 2021/11/23 - 11:56:44 | 200 |      10.143µs |       192.0.2.1 | GET      "/test/copy/race"
PASS
ok  	github.com/gin-gonic/gin	0.237s
```

I will check out it later today for finding details we ignored.

**Comment by thinkerou** [comment]
Released v1.7.6 using the code of v1.7.4 version to fix the error at first.

**Comment by Bisstocuz** [comment]
> Released v1.7.6 using the code of v1.7.4 version to fix the error at first, please see https://github.com/gin-gonic/gin/releases/tag/v1.7.6, thanks!

Hi, there! What I mean is that create a new branch from tag v1.7.4, and cherry-pick those necessary commits then put them into the new branch based on v1.7.4.

I found the errors you reported occurred with data added in #2767.

**Comment by thinkerou** [comment]
```
Hi, there! What I mean is that create a new branch from tag v1.7.4, and cherry-pick those necessary commits then put them into the new branch based on v1.7.4.
```
@Bisstocuz when I created v1.7.5 based on v1.7.4 and use cherry-pick, but have some error, I don't fix it, oh no...it's released.

**Comment by Bisstocuz** [comment]
> ```
> Hi, there! What I mean is that create a new branch from tag v1.7.4, and cherry-pick those necessary commits then put them into the new branch based on v1.7.4.
> ```
> 
> @Bisstocuz when I created v1.7.5 based on v1.7.4 and use cherry-pick, but have some error, I don't fix it, oh no...it's released.

Look at this: https://github.com/Bisstocuz/gin/commits/pre177
I create a new branch from tag v1.7.4 again and cherry-pick commits, it still work normally.
Throughout the whole process, I only need to handle the conflicts on #2828 and #2897.
So, just create a new branch from tag v1.7.4, and follow my order to cherry-pick commits from the bottom to the top.

I believe the error you meet at first has to do with the merge order.

**Comment by thinkerou** [comment]
@Bisstocuz thanks! https://github.com/gin-gonic/gin/tree/v177 ready and wait release

**Review by thinkerou — APPROVED** [review]
lgtm

**Pull request merged**
