### PR TITLE
Attempt to fix #1927

### LINKED ISSUE #1927: It seems there's cache when use c.PostForm
- With issues:
Hi all, when using c.PostForm to get parameters from ajax, it seems there's cache in it, and the values do not change for times.

- go version: 1.11.2
- gin version (or commit ref): latest
- operating system: Mac OS

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by dmarkham** [comment]
@thinkerou nice find this looks safe and needed!

**Comment by crazywako** [comment]
Will this fix also this case with files where files would be "cached"?
`		form, _ := c.MultipartForm()
		files := form.File["upload"]
`

**Comment by thinkerou** [comment]
@crazywako can you help me check? thanks!

**Comment by crazywako** [comment]
> @crazywako can you help me check? thanks!

Will test in the next 24 hours.

**Comment by crazywako** [comment]
@thinkerou Couldn't reproduce the problem anymore. So it seems fixed. I will open a issue if I find out the issue is still there.

**Comment by thinkerou** [comment]
@crazywako thanks!!! 💯

**Pull request merged**
