### PR TITLE
Let's user define how he wants to log his routes (eg. JSON, key value, or something else)

### LINKED ISSUE #1553: format log from gin gonic
Hello,

It will be great to let to user how he want to log information (json, key value, plain text) from gin gonic (e.g `debugPrintRoute`,  access log, panic).

My goal is to see something like this:
```json
{"method": "POST", "path": "/foo/", "handler": "foo.func1", "handlers": 1}
{"method": "GET", "path": "/bar/", "handler": "bar.func1", "handlers": 1}
{"method": "GET", "path": "/status", "handler": "status.func1", "handlers": 1}
```

instead of:
```
[GIN-debug] POST   /foo/                    --> foo.func1 (1 handlers)
[GIN-debug] GET    /bar/                    --> bar.func1 (1 handlers)
[GIN-debug] GET    /status                  --> status.func1 (1 handlers)
```

### PR DESCRIPTION
**Pull request by jerome-laforge**
Close #1553

### CODE REVIEW

**Comment by thinkerou** [comment]
@jerome-laforge please add some annotations to help user know how use it. thanks!

**Comment by appleboy** [comment]
@jerome-laforge Add example code in README.

**Comment by jerome-laforge** [comment]
>Add example code in README.

@appleboy I just add an example in README

**Comment by appleboy** [comment]
@thinkerou need your approval.

**Pull request merged**
