### PR TITLE
upgrade github.com/ugorji/go/codec

### PR DESCRIPTION
**Pull request by thinkerou**
ref: #1673

### CODE REVIEW

**Comment by AndreiD** [comment]
anyone wants to take a look at this please :)

**Comment by jimanvlad** [comment]
Still get similar when using gin via go modules:

```
build command-line-arguments: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.4 (/Users/jimanv/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
        github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2 (/Users/jimanv/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181209151446-772ced7fd4c2)

```

**Comment by appleboy** [comment]
@jimanvlad try `go get github.com/gin-gonic/gin@master`

**Comment by jimanvlad** [comment]
Works after explicit `go get` but assumed this pull request would have fixed the download automatically

**Pull request merged**
