### PR TITLE
[GIN-002] Add AVRO binding

### PR DESCRIPTION
**Pull request by Valentine-Mario**
- With pull requests:
  - Open your pull request against `master`
  - Your pull request should have no more than two commits, if not you should squash them.
  - It should pass all tests in the available continuous integration systems such as GitHub Actions.
  - You should add/modify tests to cover your proposed code changes.
  - If your pull request contains a new feature, please document it on the README.

### CODE REVIEW

**Comment by Valentine-Mario** [comment]
@appleboy please help review

**Comment by Valentine-Mario** [comment]
@ffhelicopter

**Comment by Valentine-Mario** [comment]
@thinkerou

**Comment by austinjp** [comment]
Hi. Just curious, was there any reason this didn't get reviewed or merged? I see the contributing repo:branch has been deleted, but the code looks good (with [one typo](https://github.com/gin-gonic/gin/pull/3098/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R683) I can see). It would be really nice to see Avro supported by Gin out of the box. Are there ways the Gin team would recommend Avro is implemented? My googling didn't reveal much.

**Pull request closed without merging**
