### PR TITLE
Abort with status and json body

### PR DESCRIPTION
**Pull request by pjgg**

### CODE REVIEW

**Comment by yoshiya0503** [comment]
Why this PR was not be merged?

I think that 4xx response with json body is very common case.

Or, is there another best practice about error handling with json?

related issue
https://github.com/gin-gonic/gin/issues/274

**Comment by yoshiya0503** [comment]
`
func Authenticate() gin.HandlerFunc {
    return func(ctx *gin.Context) {
         // error ocured
         if SomeError() {
                ctx.JSON(401, gin.H{"message": "authenticate error please login", "code": 12345})
                ctx.Abort()
                return
         }
         ctx.Next()
    }
}
`

Umm...

**Comment by appleboy** [comment]
@yoshiya0503 This feature has been merged into `develop` branch.

See https://github.com/gin-gonic/gin/blob/develop/context.go#L123-L128

You can try it using govendor tool.

**Comment by appleboy** [comment]
Also see #800 PR.

**Comment by yoshiya0503** [comment]
@appleboy Good! Oh I See ! Thank you.

**Comment by pjgg** [comment]
In develop you could find a method

https://github.com/gin-gonic/gin/blob/develop/context.go#L123-L128

That allow you abort a chain request and returns a JSON object as a
response. This object could be a customError struct.

**Pull request closed without merging**
