### PR TITLE
bump to v1.7.0 version

### PR DESCRIPTION
**Pull request by appleboy**
as title. cc @thinkerou

### CODE REVIEW

**Comment by appleboy** [comment]
@thinkerou We should add changelog before release v1.7.0?

**Comment by thinkerou** [comment]
> @thinkerou We should add changelog before release v1.7.0?

yes, thanks!

**Review by thinkerou — APPROVED** [review]

**Comment by appleboy** [comment]
@thinkerou Done. Please review again.

**Review by thinkerou — APPROVED** [review]
lgtm

**Pull request merged**
