### PR TITLE
fix(router): catch-all conflicting wildcard

### LINKED ISSUE #3796: Some 'index out of range' error in tree.go
## Router tree bug

when add a catch-all router, there may be an error reported: 

`panic: runtime error: index out of range [0] with length 0`

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()

	r.GET("/static/", func(c *gin.Context) { c.String(200, "static") })
	r.GET("/static/*file", func(c *gin.Context) { c.String(200, "static file") })

	r.Run()
}
```

## Source code

`tree.go`

```
		if len(n.path) > 0 && n.path[len(n.path)-1] == '/' {
			pathSeg := strings.SplitN(n.children[0].path, "/", 2)[0]
			panic("catch-all wildcard '" + path +
				"' in new path '" + fullPath +
				"' conflicts with existing path segment '" + pathSeg +
				"' in existing prefix '" + n.path + pathSeg +
				"'")
		}
```

this line `pathSeg := strings.SplitN(n.children[0].path, "/", 2)[0]`

actually, n node do not have any children.

## Environment

- go version: go1.20
- gin version (or commit ref): v1.9.1
- operating system: mac os

### PR DESCRIPTION
**Pull request by FirePing32**
Fixes #3796 for a specific case of `index out of range` error when multiple catch-all URLs are defined on the same prefix.

### CODE REVIEW

**Comment by FirePing32** [comment]
cc @appleboy @manucorporat

**Comment by FirePing32** [comment]
cc @thinkerou @javierprovecho

**Comment by FirePing32** [comment]
@appleboy @manucorporat Can you review this?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@FirePing32 can you take a look lint error?

**Comment by FirePing32** [comment]
@appleboy i guess the lint error is unrelated to this PR. But how did previous PRs pass the tests then ?

**Comment by appleboy** [comment]
@FirePing32 Maybe something wrong with the Lint tool. I will check it.

**Comment by FirePing32** [comment]
@appleboy any update ?

**Comment by appleboy** [comment]
I will take it before https://github.com/gin-gonic/gin/pull/3834 merge

**Comment by appleboy** [comment]
@FirePing32 Please help to rebase the master branch.

**Comment by FirePing32** [comment]
@appleboy but there aren't any conflicting changes, so this can be merged directly ?

**Comment by appleboy** [comment]
@FirePing32 We need to pass the unit testing so you must rebase the latest commit from master branch.

**Comment by FirePing32** [comment]
@appleboy Ok. Will rebase the changes.

**Comment by FirePing32** [comment]
@appleboy please review

**Comment by appleboy** [comment]
build fail 

image

**Comment by FirePing32** [comment]
@appleboy can you see if the test case is correct?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
@FirePing32 Thanks.

**Pull request merged**
