### PR TITLE
Fix panic stack trace being printed during recovery of broken pipe (#1089)

### PR DESCRIPTION
**Pull request by justinfx**
This is a proposed fix for #1089 to prevent the case of a broken pipe leading to a noisy panic stack trace. 
The `DumpRequest` output is still preserved, but the panic is avoided, which is caused by the `RecoveryWithWriter` handler trying to write headers after the body has already been written.

### CODE REVIEW

**Comment by justinfx** [comment]
I can add test coverage for this change, tomorrow, if needed for acceptance.

**Comment by justinfx** [comment]
Ok, this is failing on travis because tests currently require go-1.6 to pass, and I am using sub-tests. Is this an outdated requirement? Does code really still need to confirm to go-1.6 and do I need to replace the sub-tests with manual table tests?

**Comment by justinfx** [comment]
:bump:?

**Comment by justinfx** [comment]
Anyone care about this fix being merged?

**Comment by justinfx** [comment]
@thinkerou I have fixed the conflicts, but I unless I remove the go-1.6.x line from the travis config, it will still not be able to use sub-tests. Can you confirm if you need to keep testing against go 1.6 or can I remove that requirement in this merge?

**Comment by Huang-lin** [comment]
What is the current situation of this pr, will anyone continue to handle it?

**Comment by justinfx** [comment]
If all that is holding this up is that I am not allowed to use >go-1.6 features, I guess I can conform it.

**Comment by justinfx** [comment]
:bump: maintainers?

**Comment by thinkerou** [comment]
@justinfx have some conflict and please fix it, thanks!

**Comment by justinfx** [comment]
@thinkerou , I am finding this process very frustrating and demotivating. I've been asking for this to be merged for 8 months. When it got out of sync with master, I fixed it again. I've been asking multiple times if the travis configuration can please be updated to test > go 1.6 so that I don't have to remove the use of subtests, but there has been no answer to that. Now that it has been sitting again for a while, I am being asked to fixed the conflicts.

How many times do I need to go through this loop before it gets merged? I really want to see this fixed, but I need to know that there is a point to this process.

**Comment by thinkerou** [comment]
@justinfx so sorry about your said, we also use spare time (late at night or early morning) to review code, because we need to work, hope that you can understand, very very thanks!

Because go1.6 not support `testing.Run`, I think you should use `// +build go1.7`, now gin can't remove go1.6 from travis ci. we plan gin1.4 or gin1.5 remove it.

**Comment by justinfx** [comment]
Thanks for the build tag suggestion. I have rebased to master and added the tag to make everything pass.
I completely appreciate the time it takes to maintain open source projects in our free time. I have a couple that I also maintain. But if someone submits a working patch, I do try to get it merged soonish since they put in the work. It also takes 2 or 3 more sessions for the submitter if they have to keep rebasing to keep it in a mergeable state for the maintainers. But it is clean now so hopefully it will be merged! 
Thanks again.

**Comment by thinkerou** [comment]
@justinfx thanks, need @appleboy help review, thanks!

**Comment by justinfx** [comment]
:champagne:

**Pull request merged**
