### PR TITLE
Updated README.md to show how to use templates with same name in different directories.

### PR DESCRIPTION
**Pull request by vinceyuan**
To answer questions like #321

### CODE REVIEW

**Comment by manucorporat** [comment]
I am not sure if this should be merged. I know i have to improve the documentation for the Gin integration with templates. But how to use templates is not something Gin should care about.

If anybody wants to learn how to use the template render included in the standard library there are tons of resources out there.

**Comment by vinceyuan** [comment]
Many developers just finished the tutorials at golang website and began to use gin. I think it helps new users get started with gin easier. 

Anyway, it's up to you. Thanks

Sent from my iPhone

On 2 Jun, 2015, at 11:24 pm, Manu Mtz.-Almeida <notifications@github.com> wrote:

I am not sure if this should be merged. I know i have to improve the documentation for the Gin integration with templates. But how to use templates is not something Gin should care about.

If anybody wants to learn how to use the template render included in the standard library there are tons of resources out there.

**Comment by manucorporat** [comment]
@vinceyuan you may be right, I am going to think about that

**Comment by javierprovecho** [comment]
@vinceyuan thank you, merged in develop (0da45581399a82219b87a74ab194f01aeda60f8c)

**Pull request closed without merging**
