### PR TITLE
feat: Add support for custom validation tags

### PR DESCRIPTION
**Pull request by sudo-suhas**
`validator` allows for registration of custom validation tag - http://godoc.org/gopkg.in/go-playground/validator.v8#Validate.RegisterValidation. This adds a method to the `StructValidator` interface and implements the same in `defaultValidator`. I also added an example to the readme.

### CODE REVIEW

**Comment by appleboy** [comment]
Could you also add source code to `examples` folder? otherwise LGTM.

**Comment by sudo-suhas** [comment]
@appleboy Done. I looked at some of the other examples and also added the `[embedmd]` directive. Hope that's okay. For some reason the travis build on 1.6 is hung - https://travis-ci.org/gin-gonic/gin/builds/265011756. I tricked travis into a fresh build which passed - https://travis-ci.org/gin-gonic/gin/builds/265013726

**Comment by sudo-suhas** [comment]
Rebased(again). Please consider merging this in. Or some explanation as to why it hasn't been merged would be helpful.

**Comment by appleboy** [comment]
@sudo-suhas Thanks for your contribution. LGTM. We need the other reviewers confirm this feature. cc @tboerger @javierprovecho

**Comment by sudo-suhas** [comment]
Ok, I'll try to add some tests. Meanwhile, any pointers would be appreciated.

**Comment by javierprovecho** [comment]
@sudo-suhas a test using the new API you just added would up the coverage. This helps if that method change API args order or type, for example

**Comment by sudo-suhas** [comment]
@javierprovecho I have added a test for registering custom validation. Please take a look if anything needs to be changed or if more tests need to be added. IMHO, the `RegisterValidation` functionality is well tested by the `validator.v8` library so the current test can suffice.

**Comment by sudo-suhas** [comment]
@javierprovecho Happy to help out 😄. Truly a pleasure contributing to awesome open source projects like this one.

**Pull request merged**
