### PR TITLE
Added simple testing documentation and examples

### PR DESCRIPTION
**Pull request by firstrow**
What do you think guys? For newcomers it takes time to figure out how to test gin routes. I personally found questions on stackoverflow and couple blog posts. 
This may save a bit of time.

waiting for your ideas/proposal.

Changes:

1. Modified basic example and added test file
2. Added testing doc to readme file

### CODE REVIEW

**Comment by appleboy** [comment]
@firstrow Thanks for your contribution. Waiting for the CI build.

**Comment by firstrow** [comment]
test fails on gin_integration_test.go, which is not related to this PR 
```
Error Trace:	gin_integration_test.go:95
```

**Comment by appleboy** [comment]
@firstrow Thanks for your contribution.

**Comment by appleboy** [comment]
I fixed the build errors in `master` branch.

**Pull request merged**
