### PR TITLE
support running with socket

### PR DESCRIPTION
**Pull request by zebozhuang**
I find that gin does not support listening socket, I add it.

### CODE REVIEW

**Comment by manucorporat** [comment]
can you provide a sample code?
also, any idea about how to do an unit test?

**Comment by manucorporat** [comment]
@zebozhuang I could not merge it directly:
https://github.com/gin-gonic/gin/commit/cd6e95f0e4e05e3266e3e90f56a2501e3500e7f6

Thank you very much. You will be added to the AUTHORS file.

**Comment by zebozhuang** [comment]
Hi, I am busy these days. Could you merge it now?

**Comment by zebozhuang** [comment]
@manucorporat Hi, I am busy these days. Could you merge it now?

**Pull request merged**
