### PR TITLE
feat(context): add idiomatic binding functions for clear err managment

### LINKED ISSUE #662: Custom BindWith error managing
Hello @danslimmon, @DennyLoko, @sidbusy, @stxml, @dgsi, @kongfei605, @LeBronoMars and @tsirolnik,

First of all, sorry for delay in answering, I was just a little bit busy with university (final exams).

Regarding all the following issues (#629, #633, #636, https://github.com/danslimmon/gin/pull/1 and #661), here is what I suggest:
- Because Gin now has the API frozen (doesn't allow breaking changes in functions or behavior), I can't change the behavior of `c.BindWith()` (#661, @sidbusy), however I like the idea, so keep reading.
- I'll review and merge the PR #633 with the fix https://github.com/danslimmon/gin/pull/1 (@danslimmon, @DennyLoko).
- I propose to add two function/aliases called:
  - `c.ShouldBindWith()` implementing #661, which will allow custom error managment.
  - `c.MustBindWith()` being an alias of `c.BindWith()` and soft deprecating the last one (just a message via `fmt.Println`), for a future change of behavior, by moving `c.ShouldBindWith()` back to `c.BindWith()`.

Because I'm not a native english speaker, maybe the naming of the two new proposed functions sound strange or completely wrong, so I'm open to suggestion about this, and also about everything else in this message.

Hope I did explained correctly. Tell me your thoughts.

### PR DESCRIPTION
**Pull request by javierprovecho**
fix #662

### CODE REVIEW

**Comment by javierprovecho** [comment]
@appleboy I'm not sure what to do with `BindJSON` and others, they use `BindWith` which now uses `MustBindWith`...

**Comment by appleboy** [comment]
if we merge https://github.com/gin-gonic/gin/pull/636 PR, we can ignore this PR. right?

**Comment by javierprovecho** [comment]
@appleboy if 636 is merged, some behavior may be broken. this pr is the way to go, by using `deprecated.go` and a warning `print` for those who use `bindwith`

**Comment by sidbusy** [comment]
@javierprovecho Nice! Pls release new version ASAP, Thx!

**Comment by appleboy** [comment]
@sidbusy Yes. he is working on #871 v1.2 release.

**Pull request merged**
